// 
// Decompiled by Procyon v0.6.0
// 

package w90;

import bt0.s;
import of0.v1;
import vs1.c$a;
import rl0.p$a;
import of0.k0;
import in0.v;
import rh0.b$a;
import rl0.q$a;
import com.reddit.events.common.AnalyticsScreenReferrer;
import bx.k;
import in0.m;
import ul0.h;
import com.reddit.events.onboardingchaining.OnboardingChainingAnalytics;
import uz.i;
import com.reddit.screen.listing.saved.posts.SavedPostsListingPresenter;
import v11.f;
import n42.g;
import com.reddit.events.postsets.PostSetAnalytics;
import com.reddit.events.creatorstats.CreatorStatsAnalytics;
import of0.h1;
import of0.f1;
import com.reddit.common.localization.translations.TranslationsAnalytics;
import ou0.c;
import com.reddit.events.blocked.BlockedAccountsAnalytics;
import com.reddit.screen.BaseScreen;
import com.reddit.events.recommendations.RecommendationAnalytics;
import com.reddit.events.usermodal.UserModalAnalytics;
import com.reddit.billing.RedditBillingManager;
import com.reddit.billing.RemotePurchaseDataSource;
import sa1.b;
import ca0.o0;
import in0.j;
import af2.e;
import com.reddit.frontpage.domain.usecase.a;
import javax.inject.Provider;
import w30.d;

public final class hc
{
    public d A;
    public Provider<a> B;
    public e C;
    public Provider<ls1.a> D;
    public r40.a E;
    public Provider<rh0.a> F;
    public Provider<j> G;
    public Provider<o20.a> H;
    public Provider<vt0.a> I;
    public e J;
    public e K;
    public Provider<fo0.a> L;
    public zy.e M;
    public o0 N;
    public b O;
    public Provider<RemotePurchaseDataSource> P;
    public py.b Q;
    public Provider<RedditBillingManager> R;
    public d S;
    public zy.e T;
    public vx.d U;
    public Provider<UserModalAnalytics> V;
    public Provider<RecommendationAnalytics> W;
    public Provider<pi0.a> X;
    public mw.b Y;
    public Provider<p42.a> Z;
    public final String a;
    public x40.a a0;
    public final BaseScreen b;
    public cx.b b0;
    public final a1 c;
    public Provider<BlockedAccountsAnalytics> c0;
    public e d;
    public Provider<fx.a> d0;
    public Provider<c> e;
    public Provider<TranslationsAnalytics> e0;
    public Provider<f1> f;
    public n20.b f0;
    public Provider<h1> g;
    public Provider<CreatorStatsAnalytics> g0;
    public e h;
    public Provider<PostSetAnalytics> h0;
    public iv0.b i;
    public Provider<in0.o0> i0;
    public Provider<g> j;
    public o0 j0;
    public yq1.d k;
    public Provider<f> k0;
    public ei1.a l;
    public d00.c l0;
    public v10.e m;
    public n41.d m0;
    public mx.b n;
    public Provider<t72.a> n0;
    public Provider<jl0.d> o;
    public l40.a o0;
    public a40.g p;
    public Provider<oi0.c> p0;
    public Provider<q20.c> q;
    public o0 q0;
    public ms1.a r;
    public Provider<SavedPostsListingPresenter> r0;
    public Provider<jl0.a> s;
    public xb0.b s0;
    public i t;
    public Provider<OnboardingChainingAnalytics> t0;
    public Provider<com.reddit.screens.listing.mapper.a> u;
    public hm0.d u0;
    public Provider<wh0.a> v;
    public Provider<vs1.b> v0;
    public p40.a w;
    public Provider<vs1.a> w0;
    public h x;
    public Provider<m> x0;
    public k y;
    public Provider<kz0.b> y0;
    public o52.e z;
    
    public hc(final a1 c, final lg1.b b, final BaseScreen b2, final String a, final AnalyticsScreenReferrer analyticsScreenReferrer) {
        this.c = c;
        this.a = a;
        this.b = b2;
        this.d = af2.e.a((Object)b);
        this.e = (Provider<c>)af2.c.b((Provider)q$a.a);
        this.f = (Provider<f1>)af2.c.b((Provider)new cx.b((Provider)c.x1, (Provider)c.e, (Provider)c.L, (Provider)c.h1, (Provider)c.R1, 5));
        this.g = (Provider<h1>)af2.c.b((Provider)new x10.j((Provider)c.x1, (Provider)c.e, (Provider)c.L, (Provider)c.h1, (Provider)c.R1, 3));
        final e a2 = af2.e.a((Object)b2);
        this.h = a2;
        final iv0.b b3 = iv0.b.b((Provider)a2);
        this.i = b3;
        final Provider b4 = af2.c.b((Provider)ei1.a.b((Provider)b3));
        this.j = (Provider<g>)b4;
        this.k = yq1.d.a(b4, (Provider)c.d0);
        this.l = ei1.a.c((Provider)c.m);
        this.m = v10.e.a((Provider)c.c0, (Provider)c.m, (Provider)this.i, (Provider)c.n, (Provider)c.i, (Provider)c.B2, (Provider)c.V, (Provider)this.l, (Provider)mw.b.b(), (Provider)c.i0, (Provider)c.C2);
        this.n = mx.b.a((Provider)ht.b.b());
        this.o = (Provider<jl0.d>)af2.h.a((Provider)jl0.i.a((Provider)c.m));
        this.p = a40.g.a((Provider)c.m, (Provider)this.o, (Provider)c.n, (Provider)vg0.a.b((Provider)c.j), (Provider)c.i, (Provider)c.o, (Provider)c.p, (Provider)c.q);
        final Provider b5 = af2.c.b((Provider)ei1.a.a((Provider)this.i));
        this.q = (Provider<q20.c>)b5;
        this.r = ms1.a.b(b5, (Provider)c.z0);
        this.s = (Provider<jl0.a>)af2.h.a((Provider)jl0.g.a((Provider)c.m));
        final i c2 = uz.i.c((Provider)c.x0, (Provider)c.y0);
        this.t = c2;
        this.u = (Provider<com.reddit.screens.listing.mapper.a>)af2.c.b((Provider)x10.j.b((Provider)this.s, (Provider)c.j, (Provider)c.G, (Provider)c.c, (Provider)c2));
        final Provider b6 = af2.c.b((Provider)vg0.a.d((Provider)c.h));
        this.v = (Provider<wh0.a>)b6;
        final p40.a d = p40.a.d((Provider)c.r2, (Provider)c.J1, (Provider)this.q, b6);
        this.w = d;
        this.x = ul0.h.a((Provider)c.c, (Provider)c.j, (Provider)c.Y, (Provider)c.z2, (Provider)this.k, (Provider)c.c0, (Provider)c.A2, (Provider)c.d0, (Provider)this.m, (Provider)this.n, (Provider)c.D2, (Provider)this.p, (Provider)c.m, (Provider)c.E2, (Provider)c.k1, (Provider)c.r2, (Provider)c.F2, (Provider)c.R1, (Provider)c.V, (Provider)c.P1, (Provider)this.r, (Provider)c.J1, (Provider)this.u, (Provider)d);
        this.y = bx.k.a((Provider)c.A2, (Provider)c.E2);
        this.z = o52.e.a((Provider)this.r, (Provider)c.m, (Provider)c.P1);
        final d c3 = w30.d.c((Provider)this.y, (Provider)this.z, v40.d.a((Provider)c.Y, (Provider)c.c0, (Provider)this.k, (Provider)c.d0), (Provider)c.j, (Provider)c.z2, (Provider)this.w);
        this.A = c3;
        this.B = (Provider<a>)af2.c.b((Provider)uy.b.d((Provider)c.x1, (Provider)this.x, c3));
        this.C = af2.e.a((Object)"saved_posts");
        this.D = (Provider<ls1.a>)af2.c.b((Provider)sy.e.a((Provider)this.i, (Provider)this.h, (Provider)c.w, (Provider)c.T, (Provider)c.U, (Provider)c.V));
        this.E = r40.a.a((Provider)this.i, ms1.a.a((Provider)c.b0, (Provider)c.y), (Provider)c.m, (Provider)c.z0, (Provider)c.A0);
        final Provider b7 = af2.c.b((Provider)b$a.a);
        this.F = (Provider<rh0.a>)b7;
        this.G = (Provider<j>)af2.c.b((Provider)in0.v.a((Provider)this.i, (Provider)this.h, (Provider)this.C, (Provider)c.b0, (Provider)c.E, (Provider)c.m2, (Provider)this.D, (Provider)c.n3, (Provider)c.M1, (Provider)this.E, (Provider)c.R1, (Provider)c.n, b7, (Provider)c.o3, (Provider)c.h, (Provider)c.p3, (Provider)this.t, (Provider)c.n2, (Provider)c.A1, (Provider)c.S1, (Provider)c.j1, (Provider)c.J0));
        this.H = (Provider<o20.a>)af2.c.b((Provider)vx.d.b((Provider)this.i, (Provider)c.E, (Provider)c.w));
        this.I = (Provider<vt0.a>)af2.c.b((Provider)ug0.a.c(xb0.b.e(e40.k.b((Provider)c.l0, (Provider)c.m0, (Provider)c.e))));
        this.J = af2.e.b((Object)a);
        this.K = af2.e.b((Object)analyticsScreenReferrer);
        this.L = (Provider<fo0.a>)af2.c.b((Provider)vx.d.c((Provider)this.i, (Provider)c.N2, (Provider)c.w));
        this.M = zy.e.a((Provider)c.y, (Provider)c.e, (Provider)c.o0);
        this.N = ca0.o0.e((Provider)c.h);
        this.O = sa1.b.a((Provider)this.h);
        final Provider a3 = af2.h.a((Provider)rx.b.a((Provider)c.D0));
        this.P = (Provider<RemotePurchaseDataSource>)a3;
        this.Q = py.b.a(a3, (Provider)c.E0);
        final Provider b8 = af2.c.b((Provider)vx.c.b((Provider)this.i, (Provider)this.O, (Provider)this.Q, (Provider)c.c, (Provider)c.b0, (Provider)c.F0, (Provider)c.G0, (Provider)c.o0, (Provider)c.m, (Provider)uz.i.a((Provider)c.c, (Provider)c.K), (Provider)c.H0, (Provider)c.V));
        this.R = (Provider<RedditBillingManager>)b8;
        this.S = w30.d.a(this.D, (Provider)c.X, (Provider)c.e, (Provider)c.o0, (Provider)c.V, (Provider)ty.e.a((Provider)c.X, (Provider)c.V, (Provider)c.a0, (Provider)c.n, (Provider)c.c3, (Provider)c.c, b8, (Provider)c.r, (Provider)c.J));
        this.T = zy.e.b((Provider)this.i, (Provider)c.w, (Provider)c.T);
        this.U = vx.d.a((Provider)this.i, (Provider)this.h, (Provider)c.w);
        this.V = (Provider<UserModalAnalytics>)af2.c.b((Provider)xb0.b.d((Provider)c.h));
        this.W = (Provider<RecommendationAnalytics>)af2.c.b((Provider)vx.b.b((Provider)c.h, (Provider)this.F));
        this.X = (Provider<pi0.a>)af2.c.b((Provider)mx.b.b((Provider)c.h, (Provider)this.F));
        this.Y = mw.b.a((Provider)c.h);
        this.Z = (Provider<p42.a>)af2.c.b((Provider)nx.d.a((Provider)this.O, (Provider)c.i, (Provider)c.y, (Provider)c.k1, (Provider)c.T0, (Provider)c.m, py.b.b((Provider)c.h, (Provider)this.J), (Provider)c.e, (Provider)c.o0));
        this.a0 = x40.a.a((Provider)c.w, (Provider)c.r0, (Provider)c.s0, (Provider)c.t0, (Provider)this.i, (Provider)c.u0, (Provider)d00.c.e((Provider)c.v0, (Provider)c.t0), (Provider)c.v0);
        this.b0 = cx.b.c((Provider)this.i, (Provider)this.h, (Provider)c.w, (Provider)c.T, (Provider)c.d3);
        this.c0 = (Provider<BlockedAccountsAnalytics>)af2.c.b((Provider)of0.k0.b((Provider)c.h));
        this.d0 = (Provider<fx.a>)af2.c.b((Provider)gx.b.a((Provider)c.v1, (Provider)c.t0, (Provider)c.n, (Provider)c.w1, (Provider)c.J, (Provider)c.L));
        final Provider b9 = af2.c.b((Provider)rx.a.b((Provider)c.h));
        this.e0 = (Provider<TranslationsAnalytics>)b9;
        this.f0 = n20.b.a((Provider)this.i, (Provider)c.t3, (Provider)c.w, b9);
        this.g0 = (Provider<CreatorStatsAnalytics>)af2.c.b((Provider)ug0.a.d((Provider)c.h));
        final Provider b10 = af2.c.b((Provider)ca0.o0.c((Provider)c.h));
        this.h0 = (Provider<PostSetAnalytics>)b10;
        this.i0 = (Provider<in0.o0>)af2.c.b((Provider)in0.k0.a((Provider)this.i, (Provider)this.G, (Provider)c.i, (Provider)this.H, (Provider)c.d, (Provider)c.x1, (Provider)this.I, (Provider)this.J, (Provider)this.K, (Provider)this.x, (Provider)this.L, (Provider)c.N2, (Provider)c.q3, (Provider)c.e, (Provider)c.o0, (Provider)this.M, (Provider)c.r3, (Provider)c.i2, (Provider)c.d0, (Provider)c.W, (Provider)this.N, (Provider)this.S, (Provider)this.T, (Provider)this.U, (Provider)this.V, (Provider)this.k, (Provider)this.W, (Provider)this.X, (Provider)c.h, (Provider)c.R1, (Provider)this.Y, (Provider)this.Z, (Provider)c.e2, (Provider)this.a0, (Provider)this.b0, (Provider)this.c0, (Provider)c.s3, (Provider)this.d0, (Provider)this.F, (Provider)c.w0, (Provider)this.h, (Provider)c.J0, (Provider)c.b2, (Provider)c.r, (Provider)this.f0, (Provider)c.h3, (Provider)c.d2, (Provider)c.c, (Provider)this.s, (Provider)c.j, (Provider)this.g0, (Provider)c.u1, (Provider)c.u3, (Provider)c.w, (Provider)c.G, (Provider)c.S1, b10, (Provider)c.I1, (Provider)c.c2, (Provider)c.y0, (Provider)c.j1, (Provider)c.A1, (Provider)c.v3));
        final o0 d2 = ca0.o0.d((Provider)c.h);
        this.j0 = d2;
        this.k0 = (Provider<f>)af2.h.a((Provider)rl0.g.a((Provider)this.i, (Provider)c.x1, (Provider)this.h, (Provider)c.o0, (Provider)c.r, (Provider)this.b0, (Provider)c.w3, (Provider)c.V, d2, (Provider)c.C2, (Provider)c.l1, (Provider)c.x3));
        this.l0 = d00.c.a((Provider)this.O, (Provider)c.w);
        this.m0 = n41.d.c((Provider)this.O);
        final Provider b11 = af2.c.b((Provider)p$a.a);
        this.n0 = (Provider<t72.a>)b11;
        this.o0 = l40.a.b((Provider)c.G, (Provider)c.y3, (Provider)c.P0, (Provider)this.l0, (Provider)this.m0, b11);
        this.p0 = (Provider<oi0.c>)af2.c.b((Provider)vg0.a.a((Provider)c.h));
        this.q0 = ca0.o0.f((Provider)c.h);
        this.r0 = (Provider<SavedPostsListingPresenter>)af2.c.b((Provider)new lg1.d((Provider)this.d, (Provider)this.e, (Provider)this.f, (Provider)this.g, (Provider)this.B, (Provider)this.x, c.c, c.d2, c.j, c.j2, c.m, c.e, c.o0, (Provider)this.i0, (Provider)this.k0, (Provider)this.A, c.k1, c.V, c.C2, c.b0, (Provider)this.o0, c.z3, c.c0, (Provider)this.p0, (Provider)this.b0, (Provider)this.m, c.i, c.B2, (Provider)this.j0, (Provider)this.q0, c.e2, c.f2, (Provider)p40.a.b((Provider)c.x1, (Provider)this.e, (Provider)c.q1, (Provider)c.r), (Provider)this.H, c.L, c.h1, c.g1, c.h2));
        this.s0 = xb0.b.a((Provider)c.h);
        this.t0 = (Provider<OnboardingChainingAnalytics>)af2.c.b((Provider)ca0.o0.b((Provider)c.h));
        this.u0 = hm0.d.a((Provider)c.L1, (Provider)c.M1, (Provider)c.g2, (Provider)c.V, (Provider)c.B3, (Provider)c.l1, (Provider)this.s0, (Provider)c.C3, (Provider)c.J0, (Provider)this.X, (Provider)c.h2, (Provider)this.F, (Provider)c.y0, (Provider)c.f2, (Provider)c.v0, (Provider)c.u2, (Provider)this.s, (Provider)c.D3, (Provider)c.R1, (Provider)c.N1, (Provider)this.t0, (Provider)c.z0, (Provider)c.S1, (Provider)c.P2, (Provider)c.q, (Provider)c.J1, (Provider)ca0.o0.a((Provider)c.h), (Provider)c.u1, (Provider)c.s1, (Provider)c.u3, (Provider)c.i, (Provider)c.k3, (Provider)c.E3, (Provider)c.F3, (Provider)c.G3, (Provider)c.M0, (Provider)c.j0, (Provider)c.Z1, (Provider)this.J);
        final Provider b12 = af2.c.b((Provider)c$a.a);
        this.v0 = (Provider<vs1.b>)b12;
        final Provider b13 = af2.c.b((Provider)cx.b.a(b12, (Provider)c.q1, (Provider)c.L1, (Provider)c.M1, (Provider)c.R1));
        this.w0 = (Provider<vs1.a>)b13;
        this.x0 = (Provider<m>)af2.c.b((Provider)hx.a.a((Provider)c.g2, (Provider)this.u0, b13, (Provider)c.w));
        this.y0 = (Provider<kz0.b>)af2.c.b((Provider)ca0.o0.g((Provider)c.h));
    }
    
    public final v1 a() {
        final q20.b k4 = this.c.a.k4();
        kz0.k.N((Object)k4);
        final s o2 = this.c.a.O2();
        kz0.k.N((Object)o2);
        final r41.a y3 = this.c.a.y3();
        kz0.k.N((Object)y3);
        return new v1(k4, o2, y3);
    }
}
