// 
// Decompiled by Procyon v0.6.0
// 

package w90;

import vs1.c$a;
import of0.k0;
import e40.k;
import in0.v;
import rh0.b$a;
import com.reddit.events.common.AnalyticsScreenReferrer;
import in0.j;
import ul0.h;
import uz.i;
import q20.c;
import n42.g;
import com.reddit.events.onboardingchaining.OnboardingChainingAnalytics;
import com.reddit.events.topic.TopicAnalytics;
import com.reddit.events.postsets.PostSetAnalytics;
import com.reddit.screen.BaseScreen;
import com.reddit.events.creatorstats.CreatorStatsAnalytics;
import com.reddit.common.localization.translations.TranslationsAnalytics;
import com.reddit.events.blocked.BlockedAccountsAnalytics;
import com.reddit.events.recommendations.RecommendationAnalytics;
import com.reddit.events.usermodal.UserModalAnalytics;
import w30.d;
import com.reddit.billing.RedditBillingManager;
import com.reddit.billing.RemotePurchaseDataSource;
import sa1.b;
import ca0.o0;
import af2.e;
import o20.a;
import javax.inject.Provider;

public final class qf
{
    public Provider<a> A;
    public Provider<vt0.a> B;
    public e C;
    public e D;
    public Provider<fo0.a> E;
    public zy.e F;
    public o0 G;
    public b H;
    public Provider<RemotePurchaseDataSource> I;
    public py.b J;
    public Provider<RedditBillingManager> K;
    public d L;
    public zy.e M;
    public vx.d N;
    public Provider<UserModalAnalytics> O;
    public Provider<RecommendationAnalytics> P;
    public Provider<pi0.a> Q;
    public mw.b R;
    public Provider<p42.a> S;
    public x40.a T;
    public cx.b U;
    public Provider<BlockedAccountsAnalytics> V;
    public Provider<fx.a> W;
    public Provider<TranslationsAnalytics> X;
    public n20.b Y;
    public Provider<CreatorStatsAnalytics> Z;
    public final BaseScreen a;
    public Provider<PostSetAnalytics> a0;
    public final String b;
    public Provider<in0.o0> b0;
    public final a1 c;
    public Provider<ka0.a> c0;
    public e d;
    public Provider<TopicAnalytics> d0;
    public e e;
    public Provider<vn0.b> e0;
    public e f;
    public Provider<kz0.b> f0;
    public iv0.b g;
    public Provider<OnboardingChainingAnalytics> g0;
    public Provider<g> h;
    public Provider<vs1.b> h0;
    public yq1.d i;
    public Provider<vs1.a> i0;
    public ei1.a j;
    public v10.e k;
    public mx.b l;
    public Provider<jl0.d> m;
    public a40.g n;
    public Provider<c> o;
    public ms1.a p;
    public Provider<jl0.a> q;
    public i r;
    public Provider<com.reddit.screens.listing.mapper.a> s;
    public Provider<wh0.a> t;
    public h u;
    public e v;
    public Provider<ls1.a> w;
    public r40.a x;
    public Provider<rh0.a> y;
    public Provider<j> z;
    
    public qf(final a1 c, final vn0.c c2, final vn0.a a, final BaseScreen a2, final String b, final AnalyticsScreenReferrer analyticsScreenReferrer) {
        this.c = c;
        this.a = a2;
        this.b = b;
        this.d = af2.e.a((Object)c2);
        this.e = af2.e.a((Object)a);
        final e a3 = af2.e.a((Object)a2);
        this.f = a3;
        final iv0.b b2 = iv0.b.b((Provider)a3);
        this.g = b2;
        final Provider b3 = af2.c.b((Provider)ei1.a.b((Provider)b2));
        this.h = (Provider<g>)b3;
        this.i = yq1.d.a(b3, (Provider)c.d0);
        this.j = ei1.a.c((Provider)c.m);
        this.k = v10.e.a((Provider)c.c0, (Provider)c.m, (Provider)this.g, (Provider)c.n, (Provider)c.i, (Provider)c.B2, (Provider)c.V, (Provider)this.j, (Provider)mw.b.b(), (Provider)c.i0, (Provider)c.C2);
        this.l = mx.b.a((Provider)ht.b.b());
        this.m = (Provider<jl0.d>)af2.h.a((Provider)jl0.i.a((Provider)c.m));
        this.n = a40.g.a((Provider)c.m, (Provider)this.m, (Provider)c.n, (Provider)vg0.a.b((Provider)c.j), (Provider)c.i, (Provider)c.o, (Provider)c.p, (Provider)c.q);
        final Provider b4 = af2.c.b((Provider)ei1.a.a((Provider)this.g));
        this.o = (Provider<c>)b4;
        this.p = ms1.a.b(b4, (Provider)c.z0);
        this.q = (Provider<jl0.a>)af2.h.a((Provider)jl0.g.a((Provider)c.m));
        final i c3 = uz.i.c((Provider)c.x0, (Provider)c.y0);
        this.r = c3;
        this.s = (Provider<com.reddit.screens.listing.mapper.a>)af2.c.b((Provider)x10.j.b((Provider)this.q, (Provider)c.j, (Provider)c.G, (Provider)c.c, (Provider)c3));
        final Provider b5 = af2.c.b((Provider)vg0.a.d((Provider)c.h));
        this.t = (Provider<wh0.a>)b5;
        this.u = ul0.h.a((Provider)c.c, (Provider)c.j, (Provider)c.Y, (Provider)c.z2, (Provider)this.i, (Provider)c.c0, (Provider)c.A2, (Provider)c.d0, (Provider)this.k, (Provider)this.l, (Provider)c.D2, (Provider)this.n, (Provider)c.m, (Provider)c.E2, (Provider)c.k1, (Provider)c.r2, (Provider)c.F2, (Provider)c.R1, (Provider)c.V, (Provider)c.P1, (Provider)this.p, (Provider)c.J1, (Provider)this.s, (Provider)p40.a.d((Provider)c.r2, (Provider)c.J1, (Provider)this.o, b5));
        this.v = af2.e.a((Object)"search_results");
        this.w = (Provider<ls1.a>)af2.c.b((Provider)w30.d.b((Provider)this.g, (Provider)this.f, (Provider)c.w, (Provider)c.T, (Provider)c.U, (Provider)c.V));
        this.x = r40.a.a((Provider)this.g, ms1.a.a((Provider)c.b0, (Provider)c.y), (Provider)c.m, (Provider)c.z0, (Provider)c.A0);
        final Provider b6 = af2.c.b((Provider)b$a.a);
        this.y = (Provider<rh0.a>)b6;
        this.z = (Provider<j>)af2.c.b((Provider)in0.v.a((Provider)this.g, (Provider)this.f, (Provider)this.v, (Provider)c.b0, (Provider)c.E, (Provider)c.m2, (Provider)this.w, (Provider)c.n3, (Provider)c.M1, (Provider)this.x, (Provider)c.R1, (Provider)c.n, b6, (Provider)c.o3, (Provider)c.h, (Provider)c.p3, (Provider)this.r, (Provider)c.n2, (Provider)c.A1, (Provider)c.S1, (Provider)c.j1, (Provider)c.J0));
        this.A = (Provider<a>)af2.c.b((Provider)vx.d.b((Provider)this.g, (Provider)c.E, (Provider)c.w));
        this.B = (Provider<vt0.a>)af2.c.b((Provider)ug0.a.c(xb0.b.e(e40.k.b((Provider)c.l0, (Provider)c.m0, (Provider)c.e))));
        this.C = af2.e.b((Object)b);
        this.D = af2.e.b((Object)analyticsScreenReferrer);
        this.E = (Provider<fo0.a>)af2.c.b((Provider)vx.d.c((Provider)this.g, (Provider)c.N2, (Provider)c.w));
        this.F = zy.e.a((Provider)c.y, (Provider)c.e, (Provider)c.o0);
        this.G = o0.e((Provider)c.h);
        this.H = sa1.b.a((Provider)this.f);
        final Provider a4 = af2.h.a((Provider)rx.b.a((Provider)c.D0));
        this.I = (Provider<RemotePurchaseDataSource>)a4;
        this.J = py.b.a(a4, (Provider)c.E0);
        final Provider b7 = af2.c.b((Provider)vx.c.b((Provider)this.g, (Provider)this.H, (Provider)this.J, (Provider)c.c, (Provider)c.b0, (Provider)c.F0, (Provider)c.G0, (Provider)c.o0, (Provider)c.m, (Provider)uz.i.a((Provider)c.c, (Provider)c.K), (Provider)c.H0, (Provider)c.V));
        this.K = (Provider<RedditBillingManager>)b7;
        this.L = w30.d.a(this.w, (Provider)c.X, (Provider)c.e, (Provider)c.o0, (Provider)c.V, (Provider)ty.e.a((Provider)c.X, (Provider)c.V, (Provider)c.a0, (Provider)c.n, (Provider)c.c3, (Provider)c.c, b7, (Provider)c.r, (Provider)c.J));
        this.M = zy.e.b((Provider)this.g, (Provider)c.w, (Provider)c.T);
        this.N = vx.d.a((Provider)this.g, (Provider)this.f, (Provider)c.w);
        this.O = (Provider<UserModalAnalytics>)af2.c.b((Provider)xb0.b.d((Provider)c.h));
        this.P = (Provider<RecommendationAnalytics>)af2.c.b((Provider)vx.b.b((Provider)c.h, (Provider)this.y));
        this.Q = (Provider<pi0.a>)af2.c.b((Provider)mx.b.b((Provider)c.h, (Provider)this.y));
        this.R = mw.b.a((Provider)c.h);
        this.S = (Provider<p42.a>)af2.c.b((Provider)nx.d.a((Provider)this.H, (Provider)c.i, (Provider)c.y, (Provider)c.k1, (Provider)c.T0, (Provider)c.m, py.b.b((Provider)c.h, (Provider)this.C), (Provider)c.e, (Provider)c.o0));
        this.T = x40.a.a((Provider)c.w, (Provider)c.r0, (Provider)c.s0, (Provider)c.t0, (Provider)this.g, (Provider)c.u0, (Provider)d00.c.e((Provider)c.v0, (Provider)c.t0), (Provider)c.v0);
        this.U = cx.b.c((Provider)this.g, (Provider)this.f, (Provider)c.w, (Provider)c.T, (Provider)c.d3);
        this.V = (Provider<BlockedAccountsAnalytics>)af2.c.b((Provider)k0.b((Provider)c.h));
        this.W = (Provider<fx.a>)af2.c.b((Provider)gx.b.a((Provider)c.v1, (Provider)c.t0, (Provider)c.n, (Provider)c.w1, (Provider)c.J, (Provider)c.L));
        final Provider b8 = af2.c.b((Provider)rx.a.b((Provider)c.h));
        this.X = (Provider<TranslationsAnalytics>)b8;
        this.Y = n20.b.a((Provider)this.g, (Provider)c.t3, (Provider)c.w, b8);
        this.Z = (Provider<CreatorStatsAnalytics>)af2.c.b((Provider)ug0.a.d((Provider)c.h));
        final Provider b9 = af2.c.b((Provider)o0.c((Provider)c.h));
        this.a0 = (Provider<PostSetAnalytics>)b9;
        this.b0 = (Provider<in0.o0>)af2.c.b((Provider)in0.k0.a((Provider)this.g, (Provider)this.z, (Provider)c.i, (Provider)this.A, (Provider)c.d, (Provider)c.x1, (Provider)this.B, (Provider)this.C, (Provider)this.D, (Provider)this.u, (Provider)this.E, (Provider)c.N2, (Provider)c.q3, (Provider)c.e, (Provider)c.o0, (Provider)this.F, (Provider)c.r3, (Provider)c.i2, (Provider)c.d0, (Provider)c.W, (Provider)this.G, (Provider)this.L, (Provider)this.M, (Provider)this.N, (Provider)this.O, (Provider)this.i, (Provider)this.P, (Provider)this.Q, (Provider)c.h, (Provider)c.R1, (Provider)this.R, (Provider)this.S, (Provider)c.e2, (Provider)this.T, (Provider)this.U, (Provider)this.V, (Provider)c.s3, (Provider)this.W, (Provider)this.y, (Provider)c.w0, (Provider)this.f, (Provider)c.J0, (Provider)c.b2, (Provider)c.r, (Provider)this.Y, (Provider)c.h3, (Provider)c.d2, (Provider)c.c, (Provider)this.q, (Provider)c.j, (Provider)this.Z, (Provider)c.u1, (Provider)c.u3, (Provider)c.w, (Provider)c.G, (Provider)c.S1, b9, (Provider)c.I1, (Provider)c.c2, (Provider)c.y0, (Provider)c.j1, (Provider)c.A1, (Provider)c.v3));
        this.c0 = (Provider<ka0.a>)af2.h.a((Provider)new d00.c((Provider)c.L, (Provider)c.P1, 17));
        final Provider b10 = af2.c.b((Provider)new qb0.b((Provider)c.h, 24));
        this.d0 = (Provider<TopicAnalytics>)b10;
        this.e0 = (Provider<vn0.b>)af2.c.b((Provider)new vn0.d((Provider)this.d, (Provider)this.e, c.z4, (Provider)this.u, (Provider)this.b0, c.j2, c.o0, c.c, c.d2, c.m, (Provider)this.c0, c.c0, (Provider)this.z, b10, c.e2, c.f2, c.J, c.C0, c.h2));
        this.f0 = (Provider<kz0.b>)af2.c.b((Provider)o0.g((Provider)c.h));
        this.g0 = (Provider<OnboardingChainingAnalytics>)af2.c.b((Provider)o0.b((Provider)c.h));
        final Provider b11 = af2.c.b((Provider)c$a.a);
        this.h0 = (Provider<vs1.b>)b11;
        this.i0 = (Provider<vs1.a>)af2.c.b((Provider)cx.b.a(b11, (Provider)c.q1, (Provider)c.L1, (Provider)c.M1, (Provider)c.R1));
    }
}
