// 
// Decompiled by Procyon v0.6.0
// 

package o90;

import q90.e0;
import us0.s;
import ff0.r1;
import hl0.d$a;
import ym0.m0;
import ks1.c$a;
import ym0.v;
import hh0.b$a;
import hl0.e$a;
import se2.h;
import ym0.x$a;
import com.reddit.events.common.AnalyticsScreenReferrer;
import com.reddit.screen.BaseScreen;
import ym0.m;
import ff0.q1;
import com.reddit.screen.listing.history.HistoryListingPresenter;
import kl0.g;
import z30.l;
import z50.k1;
import ym0.q0;
import com.reddit.events.postsets.PostSetAnalytics;
import com.reddit.events.creatorstats.CreatorStatsAnalytics;
import f42.f;
import com.reddit.common.localization.translations.TranslationsAnalytics;
import cz0.c;
import com.reddit.events.blocked.BlockedAccountsAnalytics;
import ym0.k;
import com.reddit.events.recommendations.RecommendationAnalytics;
import com.reddit.events.usermodal.UserModalAnalytics;
import com.reddit.billing.RedditBillingManager;
import qz.i;
import com.reddit.billing.RemotePurchaseDataSource;
import mg0.x;
import rx.d;
import ff0.t;
import ks1.b;
import ym0.j;
import se2.e;
import com.reddit.events.onboardingchaining.OnboardingChainingAnalytics;
import fi0.a;
import javax.inject.Provider;

public final class ml
{
    public Provider<a> A;
    public Provider<OnboardingChainingAnalytics> B;
    public e C;
    public Provider<as1.a> D;
    public Provider<j> E;
    public Provider<b> F;
    public Provider<ks1.a> G;
    public e H;
    public Provider<t> I;
    public Provider<k20.a> J;
    public Provider<nt0.a> K;
    public e L;
    public e M;
    public Provider<wn0.a> N;
    public d O;
    public x P;
    public Provider<RemotePurchaseDataSource> Q;
    public i R;
    public Provider<RedditBillingManager> S;
    public oy.e T;
    public y30.d U;
    public iz.b V;
    public Provider<UserModalAnalytics> W;
    public Provider<RecommendationAnalytics> X;
    public dt.b Y;
    public Provider<h42.a> Z;
    public final dl a;
    public q40.a a0;
    public Provider<k> b;
    public f40.a b0;
    public e c;
    public Provider<BlockedAccountsAnalytics> c0;
    public e d;
    public Provider<bx.a> d0;
    public c e;
    public Provider<TranslationsAnalytics> e0;
    public Provider<f> f;
    public ox.c f0;
    public kn1.c g;
    public Provider<CreatorStatsAnalytics> g0;
    public uv0.b h;
    public Provider<PostSetAnalytics> h0;
    public r10.e i;
    public Provider<q0> i0;
    public ix.b j;
    public Provider<m11.f> j0;
    public Provider<zk0.d> k;
    public e k0;
    public k1 l;
    public xw.k l0;
    public Provider<m20.c> m;
    public vy.e m0;
    public kn1.c n;
    public f40.a n0;
    public zz.c o;
    public uv0.b o0;
    public Provider<com.reddit.screens.listing.mapper.a> p;
    public Provider<k72.a> p0;
    public Provider<mh0.a> q;
    public l q0;
    public jx.c r;
    public n10.b r0;
    public g s;
    public Provider<xf1.a> s0;
    public uv0.b t;
    public Provider<HistoryListingPresenter> t0;
    public zz.c u;
    public q1 u0;
    public uw.f v;
    public Provider<m> v0;
    public Provider<ki0.c> w;
    public Provider<cz0.b> w0;
    public Provider<gp0.c> x;
    public Provider<gu0.c> y;
    public Provider<hh0.a> z;
    
    public ml(final dl a, final wf1.c c, final gp0.d d, final BaseScreen baseScreen, final AnalyticsScreenReferrer analyticsScreenReferrer, final wf1.b b) {
        this.a = a;
        this.b = (Provider<k>)se2.c.b((Provider)x$a.a);
        this.c = se2.e.a((Object)d);
        final e a2 = se2.e.a((Object)baseScreen);
        this.d = a2;
        final c b2 = cz0.c.b((Provider)a2);
        this.e = b2;
        final Provider b3 = se2.c.b((Provider)uv0.b.c((Provider)b2));
        this.f = (Provider<f>)b3;
        this.g = kn1.c.a(b3, (Provider)a.I0);
        this.h = uv0.b.d((Provider)a.z);
        this.i = r10.e.b((Provider)a.h0, (Provider)a.z, (Provider)this.e, (Provider)a.l, (Provider)a.d, (Provider)a.I1, (Provider)a.x0, (Provider)this.h, (Provider)nx.a.a(), (Provider)a.J1, (Provider)a.B0);
        this.j = ix.b.a((Provider)id0.b.a());
        this.k = (Provider<zk0.d>)se2.h.a((Provider)zk0.i.a((Provider)a.z));
        this.l = k1.a((Provider)a.z, (Provider)this.k, (Provider)a.l, (Provider)hg0.f.c((Provider)a.t0), (Provider)a.d, (Provider)a.L1, (Provider)a.M1, (Provider)a.N1);
        final Provider b4 = se2.c.b((Provider)oa1.b.a((Provider)this.e));
        this.m = (Provider<m20.c>)b4;
        this.n = kn1.c.b(b4, (Provider)a.b0);
        final zz.c b5 = zz.c.b((Provider)a.v0, (Provider)a.w0);
        this.o = b5;
        this.p = (Provider<com.reddit.screens.listing.mapper.a>)se2.c.b((Provider)yw.b.b((Provider)a.s0, (Provider)a.t0, (Provider)a.g0, (Provider)a.u0, (Provider)b5));
        final Provider b6 = se2.c.b((Provider)mg0.x.d((Provider)a.F));
        this.q = (Provider<mh0.a>)b6;
        final jx.c b7 = jx.c.b((Provider)a.P1, (Provider)a.I, (Provider)this.m, b6);
        this.r = b7;
        this.s = kl0.g.a((Provider)a.u0, (Provider)a.t0, (Provider)a.F1, (Provider)a.G1, (Provider)this.g, (Provider)a.h0, (Provider)a.H1, (Provider)a.I0, (Provider)this.i, (Provider)this.j, (Provider)a.K1, (Provider)this.l, (Provider)a.z, (Provider)a.O1, (Provider)a.P1, (Provider)a.Q1, (Provider)a.P0, (Provider)a.x0, (Provider)a.R1, (Provider)this.n, (Provider)a.I, (Provider)this.p, (Provider)b7);
        final uv0.b e = uv0.b.e((Provider)this.d);
        this.t = e;
        final zz.c a3 = zz.c.a((Provider)e, (Provider)a.S);
        this.u = a3;
        this.v = uw.f.e((Provider)a.l3, a3);
        final Provider b8 = se2.c.b((Provider)ib0.b.a((Provider)a.F));
        this.w = (Provider<ki0.c>)b8;
        this.x = (Provider<gp0.c>)se2.c.b((Provider)q40.a.c((Provider)this.c, (Provider)this.s, (Provider)this.v, (Provider)a.q0, q1.b(b8), (Provider)a.o, (Provider)a.m3, (Provider)a.n3, (Provider)a.o3));
        this.y = (Provider<gu0.c>)se2.c.b((Provider)e$a.a);
        final Provider b9 = se2.c.b((Provider)b$a.a);
        this.z = (Provider<hh0.a>)b9;
        this.A = (Provider<a>)se2.c.b((Provider)rx.b.a((Provider)a.F, b9));
        this.B = (Provider<OnboardingChainingAnalytics>)se2.c.b((Provider)id0.b.c((Provider)a.F));
        this.C = se2.e.a((Object)"history");
        this.D = (Provider<as1.a>)se2.c.b((Provider)z30.l.b((Provider)this.e, (Provider)this.d, (Provider)a.S, (Provider)a.z0, (Provider)a.F0, (Provider)a.x0));
        this.E = (Provider<j>)se2.c.b((Provider)ym0.v.a((Provider)this.e, (Provider)this.d, (Provider)this.C, (Provider)a.M, (Provider)a.N, (Provider)a.W, (Provider)this.D, (Provider)a.Z, (Provider)a.d3, (Provider)pi.d.a((Provider)this.e, a.Q0, (Provider)a.z, (Provider)a.b0, (Provider)a.c0), (Provider)a.P0, (Provider)a.l, (Provider)this.z, (Provider)a.D2, (Provider)a.F, (Provider)a.d0, (Provider)this.o, (Provider)a.M0, (Provider)a.f0, (Provider)a.O0, (Provider)a.o1, (Provider)a.U));
        final Provider b10 = se2.c.b((Provider)c$a.a);
        this.F = (Provider<b>)b10;
        this.G = (Provider<ks1.a>)se2.c.b((Provider)yw.b.a(b10, (Provider)a.q3, (Provider)a.T0, (Provider)a.d3, (Provider)a.P0));
        this.H = se2.e.a((Object)c);
        this.I = (Provider<t>)se2.c.b((Provider)new qy.b((Provider)a.P, (Provider)a.c, (Provider)a.B3, 15));
        this.J = (Provider<k20.a>)se2.c.b((Provider)vy.e.a((Provider)this.e, (Provider)a.N, (Provider)a.S));
        this.K = (Provider<nt0.a>)se2.c.b((Provider)yr0.d.b(mg0.x.c(a.i0)));
        this.L = se2.e.a((Object)"profile");
        this.M = se2.e.b((Object)analyticsScreenReferrer);
        this.N = (Provider<wn0.a>)se2.c.b((Provider)iz.b.b((Provider)this.e, (Provider)a.r3, (Provider)a.y0, (Provider)a.S));
        this.O = rx.d.a((Provider)a.J, (Provider)a.j, (Provider)a.H);
        this.P = mg0.x.b((Provider)a.F);
        final Provider a4 = se2.h.a((Provider)nx.c.a((Provider)a.Y0));
        this.Q = (Provider<RemotePurchaseDataSource>)a4;
        this.R = qz.i.a(a4, (Provider)a.Z0);
        final Provider b11 = se2.c.b((Provider)rx.c.b((Provider)this.e, (Provider)this.t, (Provider)this.R, (Provider)a.u0, (Provider)a.M, (Provider)a.a1, (Provider)a.b1, (Provider)a.H, (Provider)a.z, (Provider)uw.f.c((Provider)a.u0, (Provider)a.e), (Provider)a.c1, (Provider)a.x0));
        this.S = (Provider<RedditBillingManager>)b11;
        this.T = oy.e.a((Provider)this.D, (Provider)a.i1, (Provider)a.j, (Provider)a.H, (Provider)a.x0, (Provider)q40.a.b((Provider)a.i1, (Provider)a.x0, (Provider)a.j1, (Provider)a.l, (Provider)a.k1, (Provider)a.u0, b11, (Provider)a.o, (Provider)a.E));
        this.U = y30.d.a((Provider)this.e, (Provider)a.S, (Provider)a.z0);
        this.V = iz.b.a((Provider)this.e, (Provider)this.d, (Provider)a.y0, (Provider)a.S);
        this.W = (Provider<UserModalAnalytics>)se2.c.b((Provider)wb0.a.b((Provider)a.F));
        this.X = (Provider<RecommendationAnalytics>)se2.c.b((Provider)uw.f.d((Provider)a.F, (Provider)this.z));
        this.Y = dt.b.a((Provider)a.F);
        this.Z = (Provider<h42.a>)se2.c.b((Provider)ez.f.a((Provider)this.t, (Provider)a.d, (Provider)a.J, (Provider)a.r0, (Provider)a.K0, (Provider)a.z, qz.i.b((Provider)a.F, (Provider)this.L), (Provider)a.j, (Provider)a.H));
        this.a0 = q40.a.a((Provider)a.S, (Provider)a.t3, (Provider)a.u3, (Provider)a.C, (Provider)this.e, (Provider)a.v3, (Provider)qz.i.c((Provider)a.w3, (Provider)a.C), (Provider)a.w3);
        this.b0 = f40.a.a((Provider)this.e, (Provider)this.d, (Provider)a.y0, (Provider)a.S, (Provider)a.z0, (Provider)a.A0);
        this.c0 = (Provider<BlockedAccountsAnalytics>)se2.c.b((Provider)wb0.a.d((Provider)a.F));
        this.d0 = (Provider<bx.a>)se2.c.b((Provider)cx.b.a((Provider)a.B, (Provider)a.C, (Provider)a.l, (Provider)a.D, (Provider)a.E, (Provider)a.c));
        final Provider b12 = se2.c.b((Provider)j20.a.a((Provider)a.F));
        this.e0 = (Provider<TranslationsAnalytics>)b12;
        this.f0 = ox.c.a((Provider)this.e, (Provider)a.x3, (Provider)a.S, b12);
        this.g0 = (Provider<CreatorStatsAnalytics>)se2.c.b((Provider)q1.f((Provider)a.F));
        final Provider b13 = se2.c.b((Provider)id0.b.d((Provider)a.F));
        this.h0 = (Provider<PostSetAnalytics>)b13;
        this.i0 = (Provider<q0>)se2.c.b((Provider)ym0.m0.a((Provider)this.e, (Provider)this.E, (Provider)a.d, (Provider)this.J, (Provider)a.n1, (Provider)a.P, (Provider)this.K, (Provider)this.L, (Provider)this.M, (Provider)this.s, (Provider)this.N, (Provider)a.r3, (Provider)a.m0, (Provider)a.j, (Provider)a.H, (Provider)this.O, (Provider)a.s3, (Provider)a.H0, (Provider)a.I0, (Provider)a.Y, (Provider)this.P, (Provider)this.T, (Provider)this.U, (Provider)this.V, (Provider)this.W, (Provider)this.g, (Provider)this.X, (Provider)this.A, (Provider)a.F, (Provider)a.P0, (Provider)this.Y, (Provider)this.Z, (Provider)a.e0, (Provider)this.a0, (Provider)this.b0, (Provider)this.c0, (Provider)a.X1, (Provider)this.d0, (Provider)this.z, (Provider)a.L, (Provider)this.d, (Provider)a.U, (Provider)a.a0, (Provider)a.o, (Provider)this.f0, (Provider)a.N0, (Provider)a.y3, (Provider)a.u0, (Provider)a.s0, (Provider)a.t0, (Provider)this.g0, (Provider)a.z3, (Provider)a.A3, (Provider)a.S, (Provider)a.g0, (Provider)a.O0, b13, (Provider)a.n0, (Provider)a.L0, (Provider)a.w0, (Provider)a.o1, (Provider)a.f0, (Provider)a.K2));
        this.j0 = (Provider<m11.f>)se2.h.a((Provider)hl0.g.a((Provider)this.e, (Provider)a.P, (Provider)this.d, (Provider)a.H, (Provider)a.o, (Provider)this.b0, (Provider)a.D0, (Provider)a.x0, id0.b.e((Provider)a.F), (Provider)a.B0, (Provider)a.C0, (Provider)a.E0));
        this.k0 = se2.e.a((Object)b);
        this.l0 = xw.k.a((Provider)a.H1, (Provider)a.O1);
        this.m0 = vy.e.b((Provider)this.n, (Provider)a.z, (Provider)a.R1);
        this.n0 = f40.a.b((Provider)this.l0, (Provider)this.m0, n10.b.a((Provider)a.F1, (Provider)a.h0, (Provider)this.g, (Provider)a.I0), (Provider)a.t0, (Provider)a.G1, (Provider)this.r);
        this.o0 = uv0.b.b((Provider)this.t);
        final Provider b14 = se2.c.b((Provider)d$a.a);
        this.p0 = (Provider<k72.a>)b14;
        this.q0 = z30.l.a((Provider)a.g0, (Provider)a.E3, (Provider)a.l3, (Provider)this.u, (Provider)this.o0, b14);
        this.r0 = n10.b.d((Provider)a.P, (Provider)this.y, (Provider)a.q3, (Provider)a.o);
        final Provider b15 = se2.c.b((Provider)new ly.b((Provider)this.e, (Provider)a.S, 28));
        this.s0 = (Provider<xf1.a>)b15;
        this.t0 = (Provider<HistoryListingPresenter>)se2.c.b((Provider)new wf1.e((Provider)this.H, a.u0, a.M, (Provider)this.I, a.P, a.C3, a.y3, a.t0, (Provider)this.i0, (Provider)this.j0, (Provider)this.s, a.j, a.H, (Provider)this.k0, a.z, (Provider)this.y, (Provider)this.n0, (Provider)this.q0, a.e0, (Provider)this.r0, (Provider)this.c0, a.F3, b15, a.l0));
        this.u0 = q1.a((Provider)a.F);
        this.v0 = (Provider<m>)se2.c.b((Provider)n10.b.c((Provider)a.H3, (Provider)xl0.d.a((Provider)a.T0, (Provider)a.d3, (Provider)a.H3, (Provider)a.x0, (Provider)a.I3, (Provider)a.C0, (Provider)this.u0, (Provider)a.j3, (Provider)a.U, (Provider)this.A, (Provider)a.l0, (Provider)this.z, (Provider)a.w0, (Provider)a.F3, (Provider)a.w3, (Provider)a.p3, (Provider)a.s0, (Provider)a.I2, (Provider)a.P0, (Provider)a.J3, (Provider)this.B, (Provider)a.b0, (Provider)a.O0, (Provider)a.D3, (Provider)a.N1, (Provider)a.I, (Provider)id0.b.b((Provider)a.F), (Provider)a.z3, (Provider)this.E, (Provider)a.m, (Provider)a.A3, (Provider)a.d, (Provider)a.m3, (Provider)a.K3, (Provider)a.L3, (Provider)a.M3, (Provider)a.N3, (Provider)a.m1, (Provider)a.G0, (Provider)this.L), (Provider)this.G, (Provider)a.S));
        this.w0 = (Provider<cz0.b>)se2.c.b((Provider)cz0.c.a((Provider)a.F));
    }
    
    public final r1 a() {
        final m20.b i4 = ((e0)this.a.a).i4();
        ui.b.n((Object)i4);
        final s l2 = ((e0)this.a.a).L2();
        ui.b.n((Object)l2);
        final i41.a w3 = ((e0)this.a.a).w3();
        ui.b.n((Object)w3);
        return new r1(i4, l2, w3);
    }
}
