// 
// Decompiled by Procyon v0.6.0
// 

package o90;

import ff0.r1;
import com.reddit.domain.modtools.newcommunityprogressv2.NewCommunityProgressV2UiMapper_Factory;
import v10.l$a;
import hl0.q$a;
import hl0.s$a;
import su0.d$a;
import hf0.n;
import ym0.m0;
import ks1.c$a;
import ym0.v;
import hh0.b$a;
import hl0.r$a;
import ym0.x$a;
import com.reddit.domain.model.streaming.StreamingEntryPointType;
import com.reddit.events.common.AnalyticsScreenReferrer;
import ff0.i1;
import ff0.g1;
import com.reddit.frontpage.ui.carousel.CarouselItemActions;
import com.reddit.domain.modtools.ratingsurvey.navigation.RatingSurveyEntryActionsDelegate;
import com.reddit.domain.modtools.newcommunityprogressv2.NewCommunityProgressV2ActionsDelegate;
import com.reddit.domain.modtools.newcommunityprogress.NewCommunityProgressActionsDelegate;
import z50.k1;
import ym0.q0;
import com.reddit.events.postsets.PostSetAnalytics;
import z30.l;
import com.reddit.events.creatorstats.CreatorStatsAnalytics;
import com.reddit.common.localization.translations.TranslationsAnalytics;
import com.reddit.events.blocked.BlockedAccountsAnalytics;
import ym0.k;
import v10.h;
import com.reddit.domain.model.streaming.StreamCorrelation;
import com.reddit.events.recommendations.RecommendationAnalytics;
import com.reddit.screen.BaseScreen;
import com.reddit.events.usermodal.UserModalAnalytics;
import ty.s;
import com.reddit.billing.RedditBillingManager;
import qz.i;
import com.reddit.billing.RemotePurchaseDataSource;
import mg0.x;
import ox.f;
import com.reddit.domain.meta.model.MetaCorrelation;
import com.reddit.listing.model.Listable;
import ym0.m;
import ff0.q1;
import ym0.j;
import com.reddit.events.communityhub.CommunityHubAnalytics;
import nx0.g;
import b40.k0;
import com.reddit.events.onboardingchaining.OnboardingChainingAnalytics;
import ca0.a;
import se2.e;
import th0.d;
import ym0.b;
import ki0.c;
import javax.inject.Provider;

public final class ue
{
    public Provider<c> A;
    public Provider<b> A0;
    public Provider<d> A1;
    public Provider<gp0.c> B;
    public e B0;
    public hx.c B1;
    public Provider<gu0.c> C;
    public Provider<a> C0;
    public Provider<ti0.b> C1;
    public Provider<hh0.a> D;
    public Provider<ba0.c> D0;
    public q30.b D1;
    public Provider<fi0.a> E;
    public Provider<y90.a> E0;
    public Provider<d00.a> E1;
    public Provider<OnboardingChainingAnalytics> F;
    public rx.b F0;
    public ik0.d F1;
    public e G;
    public k0 G0;
    public g G1;
    public Provider<as1.a> H;
    public Provider<com.reddit.frontpage.presentation.carousel.a> H0;
    public Provider<CommunityHubAnalytics> H1;
    public pi.d I;
    public Provider<vl0.d> I0;
    public iz.b I1;
    public Provider<j> J;
    public Provider<vl0.e> J0;
    public q1 J1;
    public Provider<ks1.b> K;
    public Provider<com.reddit.frontpage.presentation.carousel.c> K0;
    public Provider<m> K1;
    public Provider<ks1.a> L;
    public Provider<su0.c<Listable>> L0;
    public Provider<cz0.b> L1;
    public Provider<k20.a> M;
    public Provider<MetaCorrelation> M0;
    public Provider<nt0.a> N;
    public Provider<r72.d> N0;
    public e O;
    public Provider<r72.b> O0;
    public e P;
    public Provider<r72.g> P0;
    public Provider<wn0.a> Q;
    public e Q0;
    public rx.d R;
    public f R0;
    public x S;
    public ox.c S0;
    public Provider<RemotePurchaseDataSource> T;
    public e T0;
    public i U;
    public Provider<r72.j> U0;
    public Provider<RedditBillingManager> V;
    public ez.g V0;
    public oy.e W;
    public e W0;
    public y30.d X;
    public Provider<kk0.b> X0;
    public iz.b Y;
    public s Y0;
    public Provider<UserModalAnalytics> Z;
    public Provider<si0.g> Z0;
    public final BaseScreen a;
    public Provider<RecommendationAnalytics> a0;
    public Provider<StreamCorrelation> a1;
    public final String b;
    public dt.b b0;
    public Provider<h> b1;
    public final z0 c;
    public Provider<h42.a> c0;
    public Provider<dq0.b> c1;
    public Provider<k> d;
    public q40.a d0;
    public e d1;
    public e e;
    public f40.a e0;
    public Provider<dq0.e> e1;
    public e f;
    public Provider<BlockedAccountsAnalytics> f0;
    public ox.c f1;
    public cz0.c g;
    public Provider<bx.a> g0;
    public Provider<ei0.c> g1;
    public Provider<f42.f> h;
    public Provider<TranslationsAnalytics> h0;
    public uv0.b h1;
    public kn1.c i;
    public ox.c i0;
    public se2.b i1;
    public uv0.b j;
    public Provider<CreatorStatsAnalytics> j0;
    public l j1;
    public r10.e k;
    public Provider<PostSetAnalytics> k0;
    public v40.k k1;
    public ix.b l;
    public Provider<q0> l0;
    public i l1;
    public Provider<zk0.d> m;
    public id0.b m0;
    public Provider<pf1.e> m1;
    public hg0.f n;
    public Provider<m11.f> n0;
    public Provider<pf1.b> n1;
    public k1 o;
    public e o0;
    public Provider<NewCommunityProgressActionsDelegate> o1;
    public Provider<m20.c> p;
    public xw.k p0;
    public Provider<a31.a> p1;
    public kn1.c q;
    public vy.e q0;
    public n10.b q1;
    public Provider<zk0.a> r;
    public f40.a r0;
    public wb0.a r1;
    public zz.c s;
    public Provider<com.reddit.frontpage.domain.usecase.a> s0;
    public Provider<NewCommunityProgressV2ActionsDelegate> s1;
    public Provider<com.reddit.screens.listing.mapper.a> t;
    public q30.b t0;
    public Provider<RatingSurveyEntryActionsDelegate> t1;
    public Provider<mh0.a> u;
    public Provider<kg0.a> u0;
    public l u1;
    public jx.c v;
    public Provider<d00.b> v0;
    public uw.f v1;
    public kl0.g w;
    public Provider<CarouselItemActions> w0;
    public e w1;
    public uv0.b x;
    public Provider<g1> x0;
    public wb0.a x1;
    public zz.c y;
    public Provider<i1> y0;
    public hg0.f y1;
    public uw.f z;
    public Provider<r31.c> z0;
    public n10.b z1;
    
    public ue(final z0 c, final is1.c c2, final gp0.d d, final BaseScreen a, final AnalyticsScreenReferrer analyticsScreenReferrer, final is1.a a2, final StreamingEntryPointType streamingEntryPointType, final String s, final String s2, final ym0.l l, final com.reddit.vault.h h, final gu0.e e) {
        this.c = c;
        this.a = a;
        this.b = "community";
        this.d = (Provider<k>)se2.c.b((Provider)x$a.a);
        this.e = se2.e.a((Object)d);
        final e a3 = se2.e.a((Object)a);
        this.f = a3;
        final cz0.c b = cz0.c.b((Provider)a3);
        this.g = b;
        final Provider b2 = se2.c.b((Provider)uv0.b.c((Provider)b));
        this.h = (Provider<f42.f>)b2;
        this.i = kn1.c.a(b2, (Provider)c.d0);
        this.j = uv0.b.d((Provider)c.m);
        this.k = r10.e.b((Provider)c.c0, (Provider)c.m, (Provider)this.g, (Provider)c.n, (Provider)c.i, (Provider)c.D2, (Provider)c.V, (Provider)this.j, (Provider)nx.a.a(), (Provider)c.i0, (Provider)c.E2);
        this.l = ix.b.a((Provider)id0.b.a());
        this.m = (Provider<zk0.d>)se2.h.a((Provider)zk0.i.a((Provider)c.m));
        final hg0.f c3 = hg0.f.c((Provider)c.j);
        this.n = c3;
        this.o = z50.k1.a((Provider)c.m, (Provider)this.m, (Provider)c.n, (Provider)c3, (Provider)c.i, (Provider)c.o, (Provider)c.p, (Provider)c.q);
        final Provider b3 = se2.c.b((Provider)oa1.b.a((Provider)this.g));
        this.p = (Provider<m20.c>)b3;
        this.q = kn1.c.b(b3, (Provider)c.A0);
        this.r = (Provider<zk0.a>)se2.h.a((Provider)zk0.g.a((Provider)c.m));
        final zz.c b4 = zz.c.b((Provider)c.y0, (Provider)c.z0);
        this.s = b4;
        this.t = (Provider<com.reddit.screens.listing.mapper.a>)se2.c.b((Provider)yw.b.b((Provider)this.r, (Provider)c.j, (Provider)c.G, (Provider)c.c, (Provider)b4));
        final Provider b5 = se2.c.b((Provider)mg0.x.d((Provider)c.h));
        this.u = (Provider<mh0.a>)b5;
        final jx.c b6 = jx.c.b((Provider)c.q2, (Provider)c.M1, (Provider)this.p, b5);
        this.v = b6;
        this.w = kl0.g.a((Provider)c.c, (Provider)c.j, (Provider)c.Y, (Provider)c.B2, (Provider)this.i, (Provider)c.c0, (Provider)c.C2, (Provider)c.d0, (Provider)this.k, (Provider)this.l, (Provider)c.F2, (Provider)this.o, (Provider)c.m, (Provider)c.G2, (Provider)c.q2, (Provider)c.H2, (Provider)c.p2, (Provider)c.V, (Provider)c.I2, (Provider)this.q, (Provider)c.M1, (Provider)this.t, (Provider)b6);
        final uv0.b e2 = uv0.b.e((Provider)this.f);
        this.x = e2;
        final zz.c a4 = zz.c.a((Provider)e2, (Provider)c.w);
        this.y = a4;
        this.z = uw.f.e((Provider)c.S0, a4);
        final Provider b7 = se2.c.b((Provider)ib0.b.a((Provider)c.h));
        this.A = (Provider<c>)b7;
        this.B = (Provider<gp0.c>)se2.c.b((Provider)q40.a.c((Provider)this.e, (Provider)this.w, (Provider)this.z, (Provider)c.l3, ff0.q1.b(b7), (Provider)c.r, (Provider)c.m3, (Provider)c.n3, (Provider)c.o3));
        this.C = (Provider<gu0.c>)se2.c.b((Provider)r$a.a);
        final Provider b8 = se2.c.b((Provider)b$a.a);
        this.D = (Provider<hh0.a>)b8;
        this.E = (Provider<fi0.a>)se2.c.b((Provider)rx.b.a((Provider)c.h, b8));
        this.F = (Provider<OnboardingChainingAnalytics>)se2.c.b((Provider)id0.b.c((Provider)c.h));
        this.G = se2.e.a((Object)"subreddit_listing");
        this.H = (Provider<as1.a>)se2.c.b((Provider)z30.l.b((Provider)this.g, (Provider)this.f, (Provider)c.w, (Provider)c.T, (Provider)c.U, (Provider)c.V));
        final pi.d a5 = pi.d.a((Provider)this.g, com.reddit.metrics.a.a((Provider)c.b0, (Provider)c.y), (Provider)c.m, (Provider)c.A0, (Provider)c.B0);
        this.I = a5;
        this.J = (Provider<j>)se2.c.b((Provider)ym0.v.a((Provider)this.g, (Provider)this.f, (Provider)this.G, (Provider)c.b0, (Provider)c.E, (Provider)c.j2, (Provider)this.H, (Provider)c.u2, (Provider)c.P1, (Provider)a5, (Provider)c.p2, (Provider)c.n, (Provider)this.D, (Provider)c.v2, (Provider)c.h, (Provider)c.w2, (Provider)this.s, (Provider)c.k2, (Provider)c.D1, (Provider)c.o2, (Provider)c.m1, (Provider)c.L0));
        final Provider b9 = se2.c.b((Provider)c$a.a);
        this.K = (Provider<ks1.b>)b9;
        this.L = (Provider<ks1.a>)se2.c.b((Provider)yw.b.a(b9, (Provider)c.t1, (Provider)c.O1, (Provider)c.P1, (Provider)c.p2));
        this.M = (Provider<k20.a>)se2.c.b((Provider)vy.e.a((Provider)this.g, (Provider)c.E, (Provider)c.w));
        this.N = (Provider<nt0.a>)se2.c.b((Provider)yr0.d.b(mg0.x.c(v40.k.a((Provider)c.m0, (Provider)c.n0, (Provider)c.e))));
        this.O = se2.e.a((Object)"community");
        this.P = se2.e.b((Object)analyticsScreenReferrer);
        this.Q = (Provider<wn0.a>)se2.c.b((Provider)iz.b.b((Provider)this.g, (Provider)c.Q2, (Provider)c.j0, (Provider)c.w));
        this.R = rx.d.a((Provider)c.y, (Provider)c.e, (Provider)c.p0);
        this.S = mg0.x.b((Provider)c.h);
        final Provider a6 = se2.h.a((Provider)nx.c.a((Provider)c.E0));
        this.T = (Provider<RemotePurchaseDataSource>)a6;
        this.U = qz.i.a(a6, (Provider)c.F0);
        final Provider b10 = se2.c.b((Provider)rx.c.b((Provider)this.g, (Provider)this.x, (Provider)this.U, (Provider)c.c, (Provider)c.b0, (Provider)c.G0, (Provider)c.H0, (Provider)c.p0, (Provider)c.m, (Provider)uw.f.c((Provider)c.c, (Provider)c.K), (Provider)c.I0, (Provider)c.V));
        this.V = (Provider<RedditBillingManager>)b10;
        this.W = oy.e.a((Provider)this.H, (Provider)c.X, (Provider)c.e, (Provider)c.p0, (Provider)c.V, (Provider)q40.a.b((Provider)c.X, (Provider)c.V, (Provider)c.a0, (Provider)c.n, (Provider)c.J0, (Provider)c.c, b10, (Provider)c.r, (Provider)c.J));
        this.X = y30.d.a((Provider)this.g, (Provider)c.w, (Provider)c.T);
        this.Y = iz.b.a((Provider)this.g, (Provider)this.f, (Provider)c.j0, (Provider)c.w);
        this.Z = (Provider<UserModalAnalytics>)se2.c.b((Provider)wb0.a.b((Provider)c.h));
        this.a0 = (Provider<RecommendationAnalytics>)se2.c.b((Provider)uw.f.d((Provider)c.h, (Provider)this.D));
        this.b0 = dt.b.a((Provider)c.h);
        this.c0 = (Provider<h42.a>)se2.c.b((Provider)ez.f.a((Provider)this.x, (Provider)c.i, (Provider)c.y, (Provider)c.s1, (Provider)c.W0, (Provider)c.m, qz.i.b((Provider)c.h, (Provider)this.O), (Provider)c.e, (Provider)c.p0));
        this.d0 = q40.a.a((Provider)c.w, (Provider)c.s0, (Provider)c.t0, (Provider)c.u0, (Provider)this.g, (Provider)c.v0, (Provider)qz.i.c((Provider)c.w0, (Provider)c.u0), (Provider)c.w0);
        this.e0 = f40.a.a((Provider)this.g, (Provider)this.f, (Provider)c.j0, (Provider)c.w, (Provider)c.T, (Provider)c.f3);
        this.f0 = (Provider<BlockedAccountsAnalytics>)se2.c.b((Provider)wb0.a.d((Provider)c.h));
        this.g0 = (Provider<bx.a>)se2.c.b((Provider)cx.b.a((Provider)c.y1, (Provider)c.u0, (Provider)c.n, (Provider)c.z1, (Provider)c.J, (Provider)c.L));
        final Provider b11 = se2.c.b((Provider)j20.a.a((Provider)c.h));
        this.h0 = (Provider<TranslationsAnalytics>)b11;
        this.i0 = ox.c.a((Provider)this.g, (Provider)c.s3, (Provider)c.w, b11);
        this.j0 = (Provider<CreatorStatsAnalytics>)se2.c.b((Provider)ff0.q1.f((Provider)c.h));
        final Provider b12 = se2.c.b((Provider)id0.b.d((Provider)c.h));
        this.k0 = (Provider<PostSetAnalytics>)b12;
        this.l0 = (Provider<q0>)se2.c.b((Provider)ym0.m0.a((Provider)this.g, (Provider)this.J, (Provider)c.i, (Provider)this.M, (Provider)c.d, (Provider)c.A1, (Provider)this.N, (Provider)this.O, (Provider)this.P, (Provider)this.w, (Provider)this.Q, (Provider)c.Q2, (Provider)c.p3, (Provider)c.e, (Provider)c.p0, (Provider)this.R, (Provider)c.q3, (Provider)c.f2, (Provider)c.d0, (Provider)c.W, (Provider)this.S, (Provider)this.W, (Provider)this.X, (Provider)this.Y, (Provider)this.Z, (Provider)this.i, (Provider)this.a0, (Provider)this.E, (Provider)c.h, (Provider)c.p2, (Provider)this.b0, (Provider)this.c0, (Provider)c.a2, (Provider)this.d0, (Provider)this.e0, (Provider)this.f0, (Provider)c.r3, (Provider)this.g0, (Provider)this.D, (Provider)c.x0, (Provider)this.f, (Provider)c.L0, (Provider)c.X1, (Provider)c.r, (Provider)this.i0, (Provider)c.j3, (Provider)c.Z1, (Provider)c.c, (Provider)this.r, (Provider)c.j, (Provider)this.j0, (Provider)c.x1, (Provider)c.t3, (Provider)c.w, (Provider)c.G, (Provider)c.o2, b12, (Provider)c.L1, (Provider)c.Y1, (Provider)c.z0, (Provider)c.m1, (Provider)c.D1, (Provider)c.u3));
        final id0.b e3 = id0.b.e((Provider)c.h);
        this.m0 = e3;
        this.n0 = (Provider<m11.f>)se2.h.a((Provider)hl0.g.a((Provider)this.g, (Provider)c.A1, (Provider)this.f, (Provider)c.p0, (Provider)c.r, (Provider)this.e0, (Provider)c.v3, (Provider)c.V, e3, (Provider)c.E2, (Provider)c.n1, (Provider)c.w3));
        this.o0 = se2.e.a((Object)c2);
        this.p0 = xw.k.a((Provider)c.C2, (Provider)c.G2);
        this.q0 = vy.e.b((Provider)this.q, (Provider)c.m, (Provider)c.I2);
        final f40.a b13 = f40.a.b((Provider)this.p0, (Provider)this.q0, n10.b.a((Provider)c.Y, (Provider)c.c0, (Provider)this.i, (Provider)c.d0), (Provider)c.j, (Provider)c.B2, (Provider)this.v);
        this.r0 = b13;
        this.s0 = (Provider<com.reddit.frontpage.domain.usecase.a>)se2.c.b((Provider)q30.b.b((Provider)c.A1, (Provider)this.w, b13));
        final q30.b a7 = q30.b.a((Provider)c.m, (Provider)c.N1, (Provider)c.x0);
        this.t0 = a7;
        this.u0 = (Provider<kg0.a>)se2.c.b((Provider)jx.c.c((Provider)c.h, (Provider)c.e2, (Provider)c.O1, a7));
        final Provider b14 = se2.c.b((Provider)d00.h.a((Provider)this.g, (Provider)c.w, (Provider)c.P1, (Provider)c.D1, (Provider)c.L0));
        this.v0 = (Provider<d00.b>)b14;
        this.w0 = (Provider<CarouselItemActions>)se2.h.a((Provider)new f60.b((Provider)c.y, (Provider)c.j, this.u0, (Provider)c.r4, (Provider)c.p0, this.Z, b14, 3));
        this.x0 = (Provider<g1>)se2.c.b((Provider)new y30.d((Provider)c.A1, (Provider)c.e, (Provider)c.p2, 7));
        this.y0 = (Provider<i1>)se2.c.b((Provider)new hx.c((Provider)c.A1, (Provider)c.e, (Provider)c.L, (Provider)c.k1, (Provider)c.p2, 5));
        final Provider b15 = se2.c.b((Provider)new rx.b((Provider)this.g, (Provider)c.w, 25));
        this.z0 = (Provider<r31.c>)b15;
        this.A0 = (Provider<b>)se2.c.b((Provider)new d00.h((Provider)this.u0, b15, (Provider)this.O, (Provider)c.z2, (Provider)c.L2, 5));
        this.B0 = se2.e.a((Object)a2);
        this.C0 = (Provider<a>)se2.h.a((Provider)new zz.c((Provider)c.L, (Provider)c.I2, 18));
        this.D0 = (Provider<ba0.c>)se2.c.b((Provider)new nx.b((Provider)c.K, 28));
        this.E0 = (Provider<y90.a>)se2.c.b((Provider)y90.b$a.a);
        this.F0 = new rx.b((Provider)c.q4, (Provider)c.r, 17);
        final k0 b16 = b40.k0.b((Provider)this.t, (Provider)c.p2, (Provider)c.o2, (Provider)c.D0);
        this.G0 = b16;
        this.H0 = (Provider<com.reddit.frontpage.presentation.carousel.a>)se2.c.b((Provider)hf0.n.a((Provider)c.c0, (Provider)this.C0, (Provider)c.j, (Provider)this.D0, (Provider)c.y, (Provider)this.E0, (Provider)c.c, (Provider)this.F0, b16, (Provider)c.m));
        this.I0 = (Provider<vl0.d>)se2.c.b((Provider)new f((Provider)c.c0, (Provider)c.m, (Provider)c.M1, (Provider)this.D0, (Provider)this.G0, (Provider)c.A1, (Provider)this.E0, 5));
        final Provider b17 = se2.c.b((Provider)new vl0.f((Provider)c.V3, (Provider)this.E0, (Provider)c.e, (Provider)c.M1, (Provider)c.m, (Provider)this.G0, 0));
        this.J0 = (Provider<vl0.e>)b17;
        this.K0 = (Provider<com.reddit.frontpage.presentation.carousel.c>)se2.c.b((Provider)new ox.b((Provider)c.e, (Provider)c.r4, (Provider)this.H0, (Provider)this.I0, b17, 4));
        this.L0 = (Provider<su0.c<Listable>>)se2.c.b((Provider)d$a.a);
        this.M0 = (Provider<MetaCorrelation>)se2.c.b((Provider)s$a.a);
        final z0.z0$s9 m = c.m;
        final z0.z0$o9 p12 = c.p0;
        final z0.z0$q9 j = c.j;
        final z0.z0$t7 c4 = c.c2;
        final v10.d a8 = v10.d$a.a;
        this.N0 = (Provider<r72.d>)se2.c.b((Provider)new yw.b((Provider)m, (Provider)p12, (Provider)j, (Provider)c4, (Provider)a8, 16));
        final Provider b18 = se2.c.b((Provider)be1.h.a((Provider)c.U1));
        this.O0 = (Provider<r72.b>)b18;
        this.P0 = (Provider<r72.g>)se2.c.b((Provider)new com.reddit.metrics.a((Provider)c.U1, b18, 12));
        final e a9 = se2.e.a((Object)streamingEntryPointType);
        this.Q0 = a9;
        final z0.z0$t7 c5 = c.c2;
        final z0.z0$q9 i = c.j;
        final Provider<r72.g> p13 = this.P0;
        final z0.z0$s9 k = c.m;
        final Provider<r72.b> o0 = this.O0;
        this.R0 = new f((Provider)c5, (Provider)i, (Provider)p13, (Provider)k, (Provider)a9, (Provider)o0, (Provider)a8, 8);
        this.S0 = new ox.c((Provider)c.U1, (Provider)c.e, (Provider)o0, (Provider)a9, 17);
        this.T0 = se2.e.a((Object)s2);
        final Provider b19 = se2.c.b((Provider)new com.reddit.metrics.a((Provider)this.Q0, (Provider)c.v4, 13));
        this.U0 = (Provider<r72.j>)b19;
        this.V0 = new ez.g((Provider)c.c2, (Provider)c.j, (Provider)c.m, (Provider)c.e, (Provider)this.T0, (Provider)this.O0, (Provider)this.Q0, (Provider)c.v4, b19, (Provider)a8, 8);
        final e a10 = se2.e.a((Object)l);
        this.W0 = a10;
        this.X0 = (Provider<kk0.b>)se2.c.b((Provider)new wb0.a((Provider)a10, 24));
        this.Y0 = new s((Provider)this.N0, (Provider)c.p0, (Provider)this.R0, (Provider)this.S0, (Provider)this.V0, (Provider)this.C, (Provider)this.X0, (Provider)se2.e.a((Object)s), (Provider)this.T0, (Provider)this.Q0, (Provider)this.O0, (Provider)c.v4, (Provider)this.U0, 2);
        this.Z0 = (Provider<si0.g>)se2.c.b((Provider)new id0.b((Provider)c.h, 23));
        this.a1 = (Provider<StreamCorrelation>)se2.c.b((Provider)q$a.a);
        final Provider b20 = se2.c.b((Provider)l$a.a);
        this.b1 = (Provider<h>)b20;
        this.c1 = (Provider<dq0.b>)se2.c.b((Provider)new dq0.g((Provider)c.w, (Provider)c.m, (Provider)this.W0, (Provider)this.C, (Provider)this.Z0, (Provider)this.a1, (Provider)c.U1, (Provider)c.j, (Provider)this.Q0, (Provider)c.v4, (Provider)c.c2, (Provider)this.T0, b20, (Provider)a8, (Provider)this.g, 0));
        this.d1 = se2.e.a((Object)h);
        this.e1 = (Provider<dq0.e>)se2.c.b((Provider)new qy.b((Provider)this.p, (Provider)this.c1, (Provider)c.c2, 21));
        this.f1 = new ox.c((Provider)c.o, (Provider)c.e, (Provider)c.k, (Provider)c.q, 4);
        this.g1 = (Provider<ei0.c>)se2.c.b((Provider)wb0.a.a((Provider)c.h));
        this.h1 = uv0.b.b((Provider)this.x);
        final se2.b i2 = new se2.b();
        this.i1 = i2;
        this.j1 = z30.l.a((Provider)c.G, (Provider)c.x3, (Provider)c.S0, (Provider)this.y, (Provider)this.h1, (Provider)i2);
        this.k1 = new v40.k((Provider)c.y, (Provider)c.m, (Provider)c.r, 5);
        this.l1 = new i((Provider)c.h, (Provider)this.O, 21);
        final Provider b21 = se2.c.b((Provider)new g((Provider)this.g, (Provider)c.w, 6));
        this.m1 = (Provider<pf1.e>)b21;
        this.n1 = (Provider<pf1.b>)se2.c.b((Provider)new g40.d((Provider)this.k1, (Provider)c.e, (Provider)c.p0, (Provider)this.l1, b21, (Provider)c.k0, (Provider)c.y, (Provider)c.i, (Provider)c.m, (Provider)this.W0, (Provider)this.C, 2));
        this.o1 = (Provider<NewCommunityProgressActionsDelegate>)se2.c.b((Provider)new q60.c((Provider)this.g, (Provider)this.k1, (Provider)c.w, (Provider)c.e, (Provider)c.p0, (Provider)c.m, (Provider)this.C, (Provider)this.W0, (Provider)new id0.b((Provider)c.h, 12), (Provider)this.I, (Provider)c.u1, (Provider)c.f1, (Provider)c.n1, 1));
        final Provider b22 = se2.c.b((Provider)new cz0.c((Provider)this.g, 1));
        this.p1 = (Provider<a31.a>)b22;
        final z0.z0$j2 h2 = c.h;
        final wb0.a a11 = new wb0.a((Provider)h2, 19);
        final Provider<gu0.c> c6 = this.C;
        final e w0 = this.W0;
        final n10.b q1 = new n10.b(b22, (Provider)c6, (Provider)w0, (Provider)a11, 12);
        this.q1 = q1;
        this.r1 = new wb0.a((Provider)h2, 17);
        this.s1 = (Provider<NewCommunityProgressV2ActionsDelegate>)se2.c.b((Provider)new s21.a((Provider)this.g, (Provider)c6, (Provider)w0, (Provider)c.w, b22, (Provider)q1, (Provider)this.k1, (Provider)NewCommunityProgressV2UiMapper_Factory.create(), (Provider)c.e, (Provider)c.p0, (Provider)c.m, (Provider)this.r1, (Provider)this.I, (Provider)c.u1, (Provider)c.f1, (Provider)c.n1, 0));
        this.t1 = (Provider<RatingSurveyEntryActionsDelegate>)se2.c.b((Provider)this.q1);
        this.u1 = z30.l.c((Provider)c.m, (Provider)c.c0, (Provider)this.g, (Provider)this.h, (Provider)this.n, (Provider)d00.h.b((Provider)this.g, (Provider)c.j, (Provider)this.n, (Provider)this.h));
        this.v1 = new uw.f((Provider)c.e, (Provider)c.F2, 17);
        this.w1 = se2.e.b((Object)e);
        this.x1 = new wb0.a((Provider)c.d, 6);
        this.y1 = hg0.f.a((Provider)c.h);
        this.z1 = n10.b.d((Provider)c.A1, (Provider)this.C, (Provider)c.t1, (Provider)c.r);
        this.A1 = (Provider<d>)se2.c.b((Provider)new hg0.f((Provider)c.h, 7));
        this.B1 = new hx.c((Provider)c.c0, (Provider)c.m, (Provider)c.t1, (Provider)c.d0, (Provider)a8, 14);
        this.C1 = (Provider<ti0.b>)se2.c.b((Provider)new id0.b((Provider)c.h, 18));
        this.D1 = new q30.b((Provider)c.A1, (Provider)c.e, (Provider)c.r, 14);
        this.E1 = (Provider<d00.a>)se2.c.b((Provider)new wb0.a((Provider)this.C, 28));
        this.F1 = new ik0.d((Provider)c.y, (Provider)c.c, (Provider)c.x4, (Provider)c.a0, (Provider)w82.f.a((Provider)this.g, (Provider)c.j4), (Provider)c.Q2, (Provider)this.W0, (Provider)this.C, 4);
        this.G1 = new g((Provider)c.s, (Provider)this.o0, 12);
        this.H1 = (Provider<CommunityHubAnalytics>)se2.c.b((Provider)new q1((Provider)c.h, 6));
        this.I1 = new iz.b((Provider)this.g, (Provider)c.y, (Provider)c.y4, (Provider)c.z4, 14);
        se2.b.a((Provider)this.i1, se2.c.b((Provider)new is1.i((Provider)this.l0, (Provider)this.n0, (Provider)this.o0, (Provider)this.g, (Provider)this.s0, (Provider)c.e, (Provider)c.p0, (Provider)c.r4, (Provider)this.X, (Provider)this.w0, (Provider)this.x0, (Provider)this.y0, (Provider)c.k0, (Provider)c.c, (Provider)c.Z1, (Provider)c.s4, (Provider)c.j, (Provider)c.y, (Provider)c.g2, (Provider)c.b1, (Provider)this.A0, (Provider)this.B0, (Provider)this.K0, (Provider)c.m, (Provider)this.L0, (Provider)this.C, (Provider)this.w, (Provider)this.r0, (Provider)c.U2, (Provider)c.J1, (Provider)c.I1, (Provider)c.t4, (Provider)this.Q, (Provider)c.Q2, (Provider)this.M0, (Provider)c.t1, (Provider)c.u4, (Provider)this.Y0, (Provider)this.c1, (Provider)this.t0, (Provider)c.l2, (Provider)c.a0, (Provider)this.d1, (Provider)this.e1, (Provider)c.y3, (Provider)this.f1, (Provider)c.k, (Provider)c.o, (Provider)c.c0, (Provider)this.g1, (Provider)c.W0, (Provider)this.o, (Provider)this.j1, (Provider)this.k1, (Provider)this.n1, (Provider)this.o1, (Provider)this.s1, (Provider)NewCommunityProgressV2UiMapper_Factory.create(), (Provider)c.h2, (Provider)this.t1, (Provider)this.e0, (Provider)this.u1, (Provider)this.v1, (Provider)this.m0, (Provider)c.w4, (Provider)this.k, (Provider)c.D2, (Provider)this.w1, (Provider)this.x1, (Provider)this.y1, (Provider)c.a2, (Provider)c.b2, (Provider)this.z1, (Provider)this.E, (Provider)this.D, (Provider)this.A1, (Provider)c.i, (Provider)this.B1, (Provider)this.C1, (Provider)c.V, (Provider)c.E2, (Provider)c.s, (Provider)c.X, (Provider)this.D1, (Provider)this.P, (Provider)c.l, (Provider)c.b0, (Provider)this.M, (Provider)c.r, (Provider)c.L0, (Provider)c.L, (Provider)c.k1, (Provider)c.N2, (Provider)this.E1, (Provider)c.m1, (Provider)c.j1, (Provider)this.F1, (Provider)this.G1, (Provider)c.d2, (Provider)this.H1, (Provider)this.I1, (Provider)c.A4, 0)));
        this.J1 = ff0.q1.a((Provider)c.h);
        this.K1 = (Provider<m>)se2.c.b((Provider)n10.b.c((Provider)c.c2, (Provider)xl0.d.a((Provider)c.O1, (Provider)c.P1, (Provider)c.c2, (Provider)c.V, (Provider)c.A3, (Provider)c.n1, (Provider)this.J1, (Provider)c.B3, (Provider)c.L0, (Provider)this.E, (Provider)c.d2, (Provider)this.D, (Provider)c.z0, (Provider)c.b2, (Provider)c.w0, (Provider)c.t2, (Provider)this.r, (Provider)c.C3, (Provider)c.p2, (Provider)c.Q1, (Provider)this.F, (Provider)c.A0, (Provider)c.o2, (Provider)c.S2, (Provider)c.q, (Provider)c.M1, (Provider)id0.b.b((Provider)c.h), (Provider)c.x1, (Provider)this.J, (Provider)c.v1, (Provider)c.t3, (Provider)c.i, (Provider)c.m3, (Provider)c.D3, (Provider)c.E3, (Provider)c.F3, (Provider)c.P0, (Provider)c.k0, (Provider)c.V1, (Provider)this.O), (Provider)this.L, (Provider)c.w));
        this.L1 = (Provider<cz0.b>)se2.c.b((Provider)cz0.c.a((Provider)c.h));
    }
    
    public final r1 a() {
        final m20.b i4 = this.c.a.i4();
        ui.b.n((Object)i4);
        final us0.s l2 = this.c.a.L2();
        ui.b.n((Object)l2);
        final i41.a w3 = this.c.a.w3();
        ui.b.n((Object)w3);
        return new r1(i4, l2, w3);
    }
}
