// 
// Decompiled by Procyon v0.6.0
// 

package p70;

import q90.e0;
import com.reddit.notification.common.NotificationManagerFacade;
import com.reddit.notification.domain.bus.NotificationEventBus;
import com.reddit.branch.data.RedditBranchEventStatisticsRepository;
import com.reddit.branch.data.RedditBranchActionDataRepository;
import ej2.b0;
import xd0.s;
import com.reddit.data.onboardingtopic.RedditOnboardingChainingRepository;
import xd0.m;
import us0.o;
import us0.r;
import com.reddit.screen.notification.controller.PushNotificationController;
import com.reddit.screen.notification.ui.push.composer.NotificationComposer;
import com.reddit.screen.notification.ui.push.composer.NotificationImageComposer;
import androidx.core.app.NotificationManagerCompat;
import android.content.Context;
import sg1.f;
import sg1.j;
import sg1.l;
import sg1.g;
import sg1.k;
import sg1.h;
import o90.dl;
import bm0.f2;
import o90.jk;
import sg2.e;
import o90.xt;
import rg2.a;
import javax.inject.Inject;
import o90.ch;
import com.reddit.debug.DebugActivity;
import o90.tt;

public final class d implements tt<DebugActivity, c>
{
    public final b a;
    
    @Inject
    public d(final ch a) {
        this.a = (b)a;
    }
    
    @Override
    public final xt inject(final Object o, final a a) {
        final DebugActivity debugActivity = (DebugActivity)o;
        e.f((Object)debugActivity, "target");
        e.f((Object)a, "factory");
        final c c = a.invoke();
        final b a2 = this.a;
        final a a3 = c.a;
        final ch ch = (ch)a2;
        ch.getClass();
        a3.getClass();
        final dl a4 = ch.a;
        final jk jk = new jk(a4, a3);
        final us0.f e7 = ((e0)a4.a).E7();
        ui.b.n((Object)e7);
        debugActivity.f = e7;
        final r n2 = ((e0)a4.a).N2();
        ui.b.n((Object)n2);
        debugActivity.g = n2;
        final o x = ((e0)a4.a).X();
        ui.b.n((Object)x);
        debugActivity.h = x;
        final us0.e b1 = ((e0)a4.a).B1();
        ui.b.n((Object)b1);
        debugActivity.i = b1;
        final com.reddit.session.o e8 = ((e0)a4.a).E();
        ui.b.n((Object)e8);
        debugActivity.j = e8;
        final av.a j2 = ((e0)a4.a).j2();
        ui.b.n((Object)j2);
        debugActivity.k = j2;
        final te0.a i3 = ((e0)a4.a).I3();
        ui.b.n((Object)i3);
        debugActivity.l = i3;
        final a20.a b2 = ((e0)a4.a).B2();
        ui.b.n((Object)b2);
        debugActivity.m = b2;
        final m d = ((e0)a4.a).d();
        ui.b.n((Object)d);
        debugActivity.n = d;
        final oa0.k i4 = ((e0)a4.a).I5();
        ui.b.n((Object)i4);
        debugActivity.o = i4;
        final RedditOnboardingChainingRepository r2 = ((e0)a4.a).r2();
        ui.b.n((Object)r2);
        debugActivity.p = (wc0.b)r2;
        final us0.a j3 = ((e0)a4.a).j5();
        ui.b.n((Object)j3);
        debugActivity.q = j3;
        final ja0.b f7 = ((e0)a4.a).F7();
        ui.b.n((Object)f7);
        debugActivity.r = f7;
        final fd0.d f8 = ((e0)a4.a).F1();
        ui.b.n((Object)f8);
        debugActivity.s = f8;
        final s m6 = ((e0)a4.a).m6();
        ui.b.n((Object)m6);
        debugActivity.t = m6;
        final us0.j x2 = ((e0)a4.a).X6();
        ui.b.n((Object)x2);
        debugActivity.u = x2;
        final va0.s p2 = ((e0)a4.a).P();
        ui.b.n((Object)p2);
        debugActivity.v = p2;
        final us0.b q1 = ((e0)a4.a).Q1();
        ui.b.n((Object)q1);
        debugActivity.w = q1;
        final us0.h d2 = ((e0)a4.a).d5();
        ui.b.n((Object)d2);
        debugActivity.x = d2;
        final ce0.a y = ((e0)a4.a).y();
        ui.b.n((Object)y);
        debugActivity.y = y;
        final b0 k = ((e0)a4.a).I();
        ui.b.n((Object)k);
        debugActivity.z = k;
        final sl0.a t0 = ((e0)a4.a).T0();
        ui.b.n((Object)t0);
        debugActivity.A = t0;
        final oa0.l t2 = ((e0)a4.a).t4();
        ui.b.n((Object)t2);
        debugActivity.B = t2;
        final RedditBranchActionDataRepository d3 = ((e0)a4.a).D3();
        ui.b.n((Object)d3);
        debugActivity.C = (xz.a)d3;
        final RedditBranchEventStatisticsRepository x3 = ((e0)a4.a).x0();
        ui.b.n((Object)x3);
        debugActivity.D = (xz.c)x3;
        final cw0.a a5 = ((e0)a4.a).a();
        ui.b.n((Object)a5);
        debugActivity.E = a5;
        final f22.a u1 = ((e0)a4.a).U1();
        ui.b.n((Object)u1);
        debugActivity.F = u1;
        final va0.k d4 = ((e0)a4.a).D();
        ui.b.n((Object)d4);
        debugActivity.G = d4;
        debugActivity.H = (ye0.a)new uy1.a();
        final w70.e e9 = ((e0)a4.a).E6();
        ui.b.n((Object)e9);
        debugActivity.I = e9;
        debugActivity.J = (z70.a)new f2();
        final i51.a a6 = dl.A(a4);
        final cw0.a a7 = ((e0)a4.a).a();
        ui.b.n((Object)a7);
        final va0.b l6 = ((e0)a4.a).L6();
        ui.b.n((Object)l6);
        final h h = new h(l6);
        final sg1.c c2 = new sg1.c(jk.b());
        final w70.d v8 = ((e0)a4.a).v8();
        ui.b.n((Object)v8);
        final r51.a g0 = ((e0)a4.a).G0();
        ui.b.n((Object)g0);
        final sg1.d d5 = new sg1.d(v8, g0);
        final w70.d v9 = ((e0)a4.a).v8();
        ui.b.n((Object)v9);
        final r51.a g2 = ((e0)a4.a).G0();
        ui.b.n((Object)g2);
        final k k2 = new k(v9, g2, jk.d(), new g51.e(), new lh1.d());
        final q51.b x4 = ((e0)a4.a).x6();
        ui.b.n((Object)x4);
        final g g3 = new g(x4);
        final s m7 = ((e0)a4.a).m6();
        ui.b.n((Object)m7);
        final xd0.g n3 = ((e0)a4.a).N1();
        ui.b.n((Object)n3);
        final l l7 = new l(m7, n3);
        final NotificationEventBus y2 = ((e0)a4.a).y4();
        ui.b.n((Object)y2);
        final sg1.e e10 = new sg1.e(y2, new lh1.d());
        final sg1.a a8 = new sg1.a(jk.d(), new g51.e(), jk.b());
        final com.reddit.session.o e11 = ((e0)a4.a).E();
        ui.b.n((Object)e11);
        final yz0.a p3 = ((e0)a4.a).p3();
        ui.b.n((Object)p3);
        final j j4 = new j(h, c2, d5, k2, g3, l7, e10, a8, new sg1.b(e11, p3));
        final f f9 = new f();
        final NotificationManagerFacade b3 = jk.b();
        final NotificationManagerCompat from = NotificationManagerCompat.from((Context)a3.invoke());
        e.e((Object)from, "from(getContext())");
        final mh1.c c3 = new mh1.c(b3, a3, from, jk.d(), new g51.e(), new lh1.d());
        final g51.h h2 = new g51.h();
        final cw0.a a9 = ((e0)a4.a).a();
        ui.b.n((Object)a9);
        final va0.b l8 = ((e0)a4.a).L6();
        ui.b.n((Object)l8);
        final lh1.c c4 = new lh1.c(a3, a9, l8);
        final mb0.a p4 = ((e0)a4.a).P0();
        ui.b.n((Object)p4);
        final cw0.a a10 = ((e0)a4.a).a();
        ui.b.n((Object)a10);
        final NotificationImageComposer notificationImageComposer = new NotificationImageComposer(c4, p4, a10, new lh1.d());
        final va0.k d6 = ((e0)a4.a).D();
        ui.b.n((Object)d6);
        final w70.d v10 = ((e0)a4.a).v8();
        ui.b.n((Object)v10);
        final f51.a m8 = ((e0)a4.a).M2();
        ui.b.n((Object)m8);
        final qa0.a t3 = ((e0)a4.a).T7();
        ui.b.n((Object)t3);
        final nh1.e e12 = new nh1.e(a3, d6, v10, m8, t3);
        final nh1.d d7 = new nh1.d(a3, jk.a(), new oh1.a(new g51.e()), new g51.e());
        final va0.b l9 = ((e0)a4.a).L6();
        ui.b.n((Object)l9);
        final nh1.c c5 = new nh1.c(l9);
        final mb0.a p5 = ((e0)a4.a).P0();
        ui.b.n((Object)p5);
        final og1.e e13 = new og1.e(a3, jk.a());
        final mb0.a p6 = ((e0)a4.a).P0();
        ui.b.n((Object)p6);
        final og1.a a11 = new og1.a(a3, e13, p6);
        final og1.e e14 = new og1.e(a3, jk.a());
        final og1.f f10 = new og1.f();
        final cw0.a a12 = ((e0)a4.a).a();
        ui.b.n((Object)a12);
        final og1.b b4 = new og1.b(e14, f10, a12);
        final cw0.a a13 = ((e0)a4.a).a();
        ui.b.n((Object)a13);
        final NotificationComposer notificationComposer = new NotificationComposer(notificationImageComposer, e12, d7, c5, new nh1.b(new og1.c(p5, a11, b4, a13), new oh1.a(new g51.e())), new mh1.a(a3, new mh1.b()), jk.c());
        final Context l10 = ((e0)a4.a).l();
        ui.b.n((Object)l10);
        final lh1.d d8 = new lh1.d();
        final mh1.d c6 = jk.c();
        final va0.b l11 = ((e0)a4.a).L6();
        ui.b.n((Object)l11);
        debugActivity.K = new PushNotificationController(a6, a7, j4, f9, c3, h2, notificationComposer, new rg1.d(l10, d8, c6, l11));
        final w70.h h3 = ((e0)a4.a).H0();
        ui.b.n((Object)h3);
        debugActivity.L = h3;
        final yy1.j h4 = ((e0)a4.a).H3();
        ui.b.n((Object)h4);
        debugActivity.M = h4;
        debugActivity.N = (ly1.a)a4.P3();
        return new xt((Object)jk);
    }
}
