// 
// Decompiled by Procyon v0.6.0
// 

package pe;

import ie.k4;
import ie.r4;
import java.util.Map;
import android.content.Context;
import ij.i;
import ij.h;
import ij.j;
import lq0.k;
import o90.f3;
import lw0.b;
import pd.r;
import cg.m0;
import np.a;
import java.util.HashSet;
import java.util.Collections;
import java.util.ArrayList;
import java.util.Set;
import java.util.List;

public final class r2
{
    public static final q2 A;
    public static final q2 A0;
    public static final q2 B;
    public static final q2 B0;
    public static final q2 C;
    public static final q2 D;
    public static final q2 E;
    public static final q2 F;
    public static final q2 G;
    public static final q2 H;
    public static final q2 I;
    public static final q2 J;
    public static final q2 K;
    public static final q2 L;
    public static final q2 M;
    public static final q2 N;
    public static final q2 O;
    public static final q2 P;
    public static final q2 Q;
    public static final q2 R;
    public static final q2 S;
    public static final q2 T;
    public static final q2 U;
    public static final q2 V;
    public static final q2 W;
    public static final q2 X;
    public static final q2 Y;
    public static final q2 Z;
    public static final List a;
    public static final q2 a0;
    public static final Set b;
    public static final q2 b0;
    public static final q2 c;
    public static final q2 c0;
    public static final q2 d;
    public static final q2 d0;
    public static final q2 e;
    public static final q2 e0;
    public static final q2 f;
    public static final q2 f0;
    public static final q2 g;
    public static final q2 g0;
    public static final q2 h;
    public static final q2 h0;
    public static final q2 i;
    public static final q2 i0;
    public static final q2 j;
    public static final q2 j0;
    public static final q2 k;
    public static final q2 k0;
    public static final q2 l;
    public static final q2 l0;
    public static final q2 m;
    public static final q2 m0;
    public static final q2 n;
    public static final q2 n0;
    public static final q2 o;
    public static final q2 o0;
    public static final q2 p;
    public static final q2 p0;
    public static final q2 q;
    public static final q2 q0;
    public static final q2 r;
    public static final q2 r0;
    public static final q2 s;
    public static final q2 s0;
    public static final q2 t;
    public static final q2 t0;
    public static final q2 u;
    public static final q2 u0;
    public static final q2 v;
    public static final q2 v0;
    public static final q2 w;
    public static final q2 w0;
    public static final q2 x;
    public static final q2 x0;
    public static final q2 y;
    public static final q2 y0;
    public static final q2 z;
    public static final q2 z0;
    
    static {
        a = Collections.synchronizedList(new ArrayList<Object>());
        b = Collections.synchronizedSet(new HashSet<Object>());
        final Long value = 10000L;
        c = a("measurement.ad_id_cache_time", value, value, (p2)np.a.j);
        final Long value2 = 86400000L;
        d = a("measurement.monitoring.sample_period_millis", value2, value2, (p2)cg.m0.a0);
        final Long value3 = 3600000L;
        e = a("measurement.config.cache_time", value2, value3, (p2)pe.y.f);
        f = a("measurement.config.url_scheme", "https", "https", (p2)pe.i0.f);
        g = a("measurement.config.url_authority", "app-measurement.com", "app-measurement.com", (p2)pe.v0.f);
        final Integer value4 = 100;
        h = a("measurement.upload.max_bundles", value4, value4, (p2)h1.f);
        final Integer value5 = 65536;
        i = a("measurement.upload.max_batch_size", value5, value5, (p2)u1.f);
        j = a("measurement.upload.max_bundle_size", value5, value5, (p2)g2.f);
        final Integer value6 = 1000;
        k = a("measurement.upload.max_events_per_bundle", value6, value6, (p2)k2.f);
        final Integer value7 = 100000;
        l = a("measurement.upload.max_events_per_day", value7, value7, (p2)m2.f);
        m = a("measurement.upload.max_error_events_per_day", value6, value6, (p2)pe.d0.f);
        final Integer value8 = 50000;
        n = a("measurement.upload.max_public_events_per_day", value8, value8, (p2)pe.p0.f);
        final Integer value9 = 10000;
        o = a("measurement.upload.max_conversions_per_day", value9, value9, (p2)a1.f);
        final Integer value10 = 10;
        p = a("measurement.upload.max_realtime_events_per_day", value10, value10, (p2)m1.f);
        q = a("measurement.store.max_stored_events_per_app", value7, value7, (p2)x1.f);
        r = a("measurement.upload.url", "https://app-measurement.com/a", "https://app-measurement.com/a", (p2)i2.f);
        final Long value11 = 43200000L;
        s = a("measurement.upload.backoff_period", value11, value11, (p2)n2.f);
        a("measurement.upload.window_interval", value3, value3, (p2)o2.f);
        t = a("measurement.upload.interval", value3, value3, (p2)pd.r.f);
        u = a("measurement.upload.realtime_upload_interval", value, value, (p2)lw0.b.J0);
        final Long value12 = 1000L;
        v = a("measurement.upload.debug_upload_interval", value12, value12, (p2)yd.b.o);
        final Long value13 = 500L;
        w = a("measurement.upload.minimum_delay", value13, value13, (p2)nn0.a.k);
        final Long value14 = 60000L;
        x = a("measurement.alarm_manager.minimum_interval", value14, value14, (p2)ml0.a.r);
        y = a("measurement.upload.stale_data_deletion_interval", value2, value2, (p2)f3.f);
        final Long value15 = 604800000L;
        z = a("measurement.upload.refresh_blacklisted_config_interval", value15, value15, (p2)mf1.a.k);
        final Long value16 = 15000L;
        A = a("measurement.upload.initial_upload_delay_time", value16, value16, (p2)lq0.k.l);
        final Long value17 = 1800000L;
        B = a("measurement.upload.retry_time", value17, value17, (p2)ij.j.f);
        final Integer value18 = 6;
        C = a("measurement.upload.retry_count", value18, value18, (p2)pe.x.f);
        final Long value19 = 2419200000L;
        D = a("measurement.upload.max_queue_time", value19, value19, (p2)vl.a.r);
        final Integer value20 = 4;
        E = a("measurement.lifetimevalue.max_currency_tracked", value20, value20, (p2)ui.b.w);
        final Integer value21 = 200;
        F = a("measurement.audience.filter_result_max_count", value21, value21, (p2)pe.z.f);
        final Integer value22 = 25;
        G = a("measurement.upload.max_public_user_properties", value22, value22, null);
        final Integer value23 = 500;
        H = a("measurement.upload.max_event_name_cardinality", value23, value23, null);
        I = a("measurement.upload.max_public_event_params", value22, value22, null);
        final Long value24 = 5000L;
        J = a("measurement.service_client.idle_disconnect_millis", value24, value24, (p2)pe.a0.f);
        final Boolean false = Boolean.FALSE;
        K = a("measurement.test.boolean_flag", false, false, (p2)ij.h.f);
        L = a("measurement.test.string_flag", "---", "---", (p2)ij.i.f);
        final Long value25 = -1L;
        M = a("measurement.test.long_flag", value25, value25, (p2)pe.b0.f);
        final Integer value26 = -2;
        N = a("measurement.test.int_flag", value26, value26, (p2)pe.c0.f);
        final Double value27 = -3.0;
        O = a("measurement.test.double_flag", value27, value27, (p2)pe.e0.f);
        final Integer value28 = 50;
        P = a("measurement.experiment.max_ids", value28, value28, (p2)pe.f0.f);
        Q = a("measurement.max_bundles_per_iteration", value4, value4, (p2)pe.g0.f);
        R = a("measurement.sdk.attribution.cache.ttl", value15, value15, (p2)pe.h0.f);
        final Long value29 = 7200000L;
        S = a("measurement.redaction.app_instance_id.ttl", value29, value29, (p2)pe.k0.f);
        final Boolean true = Boolean.TRUE;
        a("measurement.collection.log_event_and_bundle_v2", true, true, (p2)pe.l0.f);
        T = a("measurement.quality.checksum", false, false, null);
        U = a("measurement.audience.use_bundle_end_timestamp_for_non_sequence_property_filters", false, false, (p2)pe.m0.f);
        V = a("measurement.audience.refresh_event_count_filters_timestamp", false, false, (p2)pe.n0.f);
        W = a("measurement.audience.use_bundle_timestamp_for_event_count_filters", false, false, (p2)pe.o0.f);
        X = a("measurement.sdk.collection.retrieve_deeplink_from_bow_2", true, true, (p2)pe.q0.f);
        Y = a("measurement.sdk.collection.last_deep_link_referrer_campaign2", false, false, (p2)pe.r0.f);
        Z = a("measurement.lifecycle.app_in_background_parameter", false, false, (p2)pe.s0.f);
        a0 = a("measurement.integration.disable_firebase_instance_id", false, false, (p2)pe.t0.f);
        b0 = a("measurement.collection.service.update_with_analytics_fix", false, false, (p2)pe.u0.f);
        c0 = a("measurement.client.firebase_feature_rollout.v1.enable", true, true, (p2)pe.w0.f);
        d0 = a("measurement.client.sessions.check_on_reset_and_enable2", true, true, (p2)pe.x0.f);
        a("measurement.collection.synthetic_data_mitigation", false, false, (p2)pe.y0.f);
        final Integer value30 = 203600;
        e0 = a("measurement.service.storage_consent_support_version", value30, value30, (p2)pe.z0.f);
        a("measurement.client.click_identifier_control.dev", false, false, (p2)b1.f);
        a("measurement.service.click_identifier_control", false, false, (p2)c1.f);
        f0 = a("measurement.module.pixie.fix_array", true, true, (p2)d1.f);
        g0 = a("measurement.adid_zero.only_request_adid_if_enabled", true, true, (p2)e1.f);
        h0 = a("measurement.service.refactor.package_side_screen", true, true, (p2)f1.f);
        a("measurement.enhanced_campaign.service", true, true, (p2)g1.f);
        i0 = a("measurement.enhanced_campaign.client", true, true, (p2)i1.f);
        j0 = a("measurement.enhanced_campaign.srsltid.client", true, true, (p2)j1.f);
        a("measurement.enhanced_campaign.srsltid.service", true, true, (p2)l1.f);
        k0 = a("measurement.service.store_null_safelist", true, true, (p2)n1.f);
        l0 = a("measurement.service.store_safelist", true, true, (p2)o1.f);
        m0 = a("measurement.redaction.no_aiid_in_config_request", true, true, (p2)p1.f);
        n0 = a("measurement.redaction.config_redacted_fields", true, true, (p2)q1.f);
        o0 = a("measurement.redaction.upload_redacted_fields", true, true, (p2)r1.f);
        p0 = a("measurement.redaction.upload_subdomain_override", true, true, (p2)s1.f);
        q0 = a("measurement.redaction.device_info", true, true, (p2)t1.f);
        r0 = a("measurement.redaction.user_id", true, true, (p2)v1.f);
        s0 = a("measurement.redaction.google_signals", true, true, (p2)w1.f);
        t0 = a("measurement.collection.enable_session_stitching_token.service", false, false, (p2)y1.f);
        u0 = a("measurement.collection.enable_session_stitching_token.client.dev", false, false, (p2)z1.f);
        v0 = a("measurement.redaction.app_instance_id", true, true, (p2)a2.f);
        w0 = a("measurement.redaction.populate_ephemeral_app_instance_id", true, true, (p2)b2.f);
        x0 = a("measurement.redaction.enhanced_uid", true, true, (p2)c2.f);
        y0 = a("measurement.redaction.e_tag", true, true, (p2)d2.f);
        z0 = a("measurement.redaction.client_ephemeral_aiid_generation", true, true, (p2)e2.f);
        A0 = a("measurement.redaction.retain_major_os_version", true, true, (p2)f2.f);
        a("measurement.redaction.scion_payload_generator", false, false, (p2)h2.f);
        B0 = a("measurement.audience.dynamic_filters.oob_fix", true, true, (p2)j2.f);
    }
    
    public static q2 a(final String s, final Object o, final Object o2, final p2 p4) {
        final q2 q2 = new q2(s, o, o2, p4);
        r2.a.add(q2);
        return q2;
    }
    
    public static Map b(final Context context) {
        final k4 a = k4.a(context.getContentResolver(), r4.a(), (Runnable)pe.v.f);
        Map<Object, Object> map;
        if (a == null) {
            map = Collections.emptyMap();
        }
        else {
            map = a.b();
        }
        return map;
    }
}
