// 
// Decompiled by Procyon v0.6.0
// 

package q70;

import q90.e0;
import com.reddit.notification.common.NotificationManagerFacade;
import com.reddit.notification.domain.bus.NotificationEventBus;
import com.reddit.branch.data.RedditBranchEventStatisticsRepository;
import com.reddit.branch.data.RedditBranchActionDataRepository;
import zi2.c0;
import ws0.r;
import ws0.i;
import xd0.s;
import com.reddit.data.onboardingtopic.RedditOnboardingChainingRepository;
import xd0.m;
import com.reddit.session.n;
import ws0.q;
import ws0.u;
import com.reddit.screen.notification.controller.PushNotificationController;
import com.reddit.screen.notification.ui.push.composer.NotificationComposer;
import com.reddit.screen.notification.ui.push.composer.NotificationImageComposer;
import androidx.core.app.NotificationManagerCompat;
import android.content.Context;
import pg1.f;
import pg1.j;
import pg1.l;
import pg1.g;
import pg1.k;
import pg1.h;
import o90.lk;
import em0.m2;
import o90.rj;
import ng2.e;
import o90.ht;
import mg2.a;
import javax.inject.Inject;
import o90.hg;
import com.reddit.debug.DebugActivity;
import o90.dt;

public final class d implements dt<DebugActivity, c>
{
    public final b a;
    
    @Inject
    public d(final hg a) {
        this.a = (b)a;
    }
    
    public final ht inject(final Object o, final a a) {
        final DebugActivity debugActivity = (DebugActivity)o;
        e.f((Object)debugActivity, "target");
        e.f((Object)a, "factory");
        final c c = (c)a.invoke();
        final b a2 = this.a;
        final a a3 = c.a;
        final hg hg = (hg)a2;
        hg.getClass();
        a3.getClass();
        final lk a4 = hg.a;
        final rj rj = new rj(a4, a3);
        final ws0.f n7 = ((e0)a4.a).N7();
        zd.b.r(n7);
        debugActivity.f = n7;
        final u p2 = ((e0)a4.a).P2();
        zd.b.r(p2);
        debugActivity.g = p2;
        final q x = ((e0)a4.a).X();
        zd.b.r(x);
        debugActivity.h = x;
        final ws0.e c2 = ((e0)a4.a).C1();
        zd.b.r(c2);
        debugActivity.i = c2;
        final n e = ((e0)a4.a).E();
        zd.b.r(e);
        debugActivity.j = e;
        final av.a m2 = ((e0)a4.a).m2();
        zd.b.r(m2);
        debugActivity.k = m2;
        final te0.a l3 = ((e0)a4.a).L3();
        zd.b.r(l3);
        debugActivity.l = l3;
        final d20.a d2 = ((e0)a4.a).D2();
        zd.b.r(d2);
        debugActivity.m = d2;
        final m d3 = ((e0)a4.a).d();
        zd.b.r(d3);
        debugActivity.n = d3;
        final pa0.k p3 = ((e0)a4.a).P5();
        zd.b.r(p3);
        debugActivity.o = p3;
        final RedditOnboardingChainingRepository u2 = ((e0)a4.a).u2();
        zd.b.r(u2);
        debugActivity.p = (wc0.b)u2;
        final ws0.a p4 = ((e0)a4.a).p5();
        zd.b.r(p4);
        debugActivity.q = p4;
        final ka0.b o2 = ((e0)a4.a).O7();
        zd.b.r(o2);
        debugActivity.r = o2;
        final fd0.d g1 = ((e0)a4.a).G1();
        zd.b.r(g1);
        debugActivity.s = g1;
        final s t6 = ((e0)a4.a).t6();
        zd.b.r(t6);
        debugActivity.t = t6;
        final i e2 = ((e0)a4.a).e2();
        zd.b.r(e2);
        debugActivity.u = e2;
        final ws0.k f7 = ((e0)a4.a).f7();
        zd.b.r(f7);
        debugActivity.v = f7;
        final r r6 = ((e0)a4.a).R6();
        zd.b.r(r6);
        debugActivity.w = r6;
        final wa0.r p5 = ((e0)a4.a).P();
        zd.b.r(p5);
        debugActivity.x = p5;
        final ws0.b s1 = ((e0)a4.a).S1();
        zd.b.r(s1);
        debugActivity.y = s1;
        final ws0.h j5 = ((e0)a4.a).j5();
        zd.b.r(j5);
        debugActivity.z = j5;
        final ce0.a y = ((e0)a4.a).y();
        zd.b.r(y);
        debugActivity.A = y;
        final c0 i = ((e0)a4.a).I();
        zd.b.r(i);
        debugActivity.B = i;
        final vl0.a t7 = ((e0)a4.a).T0();
        zd.b.r(t7);
        debugActivity.C = t7;
        final pa0.l x2 = ((e0)a4.a).x4();
        zd.b.r(x2);
        debugActivity.D = x2;
        final RedditBranchActionDataRepository g2 = ((e0)a4.a).G3();
        zd.b.r(g2);
        debugActivity.E = (zz.a)g2;
        final RedditBranchEventStatisticsRepository x3 = ((e0)a4.a).x0();
        zd.b.r(x3);
        debugActivity.F = (zz.c)x3;
        final dw0.a a5 = ((e0)a4.a).a();
        zd.b.r(a5);
        debugActivity.G = a5;
        final x12.a w1 = ((e0)a4.a).W1();
        zd.b.r(w1);
        debugActivity.H = w1;
        final wa0.j d4 = ((e0)a4.a).D();
        zd.b.r(d4);
        debugActivity.I = d4;
        debugActivity.J = (ye0.a)new my1.a();
        final w70.e l4 = ((e0)a4.a).L6();
        zd.b.r(l4);
        debugActivity.K = l4;
        debugActivity.L = (z70.a)new m2();
        final m51.a d5 = lk.D(a4);
        final dw0.a a6 = ((e0)a4.a).a();
        zd.b.r(a6);
        final wa0.b t8 = ((e0)a4.a).T6();
        zd.b.r(t8);
        final h h = new h(t8);
        final pg1.c c3 = new pg1.c(rj.b());
        final w70.d f8 = ((e0)a4.a).F8();
        zd.b.r(f8);
        final v51.a g3 = ((e0)a4.a).G0();
        zd.b.r(g3);
        final pg1.d d6 = new pg1.d(f8, g3);
        final w70.d f9 = ((e0)a4.a).F8();
        zd.b.r(f9);
        final v51.a g4 = ((e0)a4.a).G0();
        zd.b.r(g4);
        final k k = new k(f9, g4, rj.d(), new k51.e(), new ih1.d());
        final u51.b e3 = ((e0)a4.a).E6();
        zd.b.r(e3);
        final g g5 = new g(e3);
        final s t9 = ((e0)a4.a).t6();
        zd.b.r(t9);
        final xd0.g o3 = ((e0)a4.a).O1();
        zd.b.r(o3);
        final l l5 = new l(t9, o3);
        final NotificationEventBus c4 = ((e0)a4.a).C4();
        zd.b.r(c4);
        final pg1.e e4 = new pg1.e(c4, new ih1.d());
        final pg1.a a7 = new pg1.a(rj.d(), new k51.e(), rj.b());
        final n e5 = ((e0)a4.a).E();
        zd.b.r(e5);
        final b01.a r7 = ((e0)a4.a).r3();
        zd.b.r(r7);
        final j j6 = new j(h, c3, d6, k, g5, l5, e4, a7, new pg1.b(e5, r7));
        final f f10 = new f();
        final NotificationManagerFacade b = rj.b();
        final NotificationManagerCompat from = NotificationManagerCompat.from((Context)a3.invoke());
        ng2.e.e((Object)from, "from(getContext())");
        final jh1.c c5 = new jh1.c(b, a3, from, rj.d(), new k51.e(), new ih1.d());
        final k51.h h2 = new k51.h();
        final dw0.a a8 = ((e0)a4.a).a();
        zd.b.r(a8);
        final wa0.b t10 = ((e0)a4.a).T6();
        zd.b.r(t10);
        final ih1.c c6 = new ih1.c(a3, a8, t10);
        final nb0.a p6 = ((e0)a4.a).P0();
        zd.b.r(p6);
        final dw0.a a9 = ((e0)a4.a).a();
        zd.b.r(a9);
        final NotificationImageComposer notificationImageComposer = new NotificationImageComposer(c6, p6, a9, new ih1.d());
        final wa0.j d7 = ((e0)a4.a).D();
        zd.b.r(d7);
        final w70.d f11 = ((e0)a4.a).F8();
        zd.b.r(f11);
        final j51.a o4 = ((e0)a4.a).O2();
        zd.b.r(o4);
        final ra0.a d8 = ((e0)a4.a).d8();
        zd.b.r(d8);
        final kh1.e e6 = new kh1.e(a3, d7, f11, o4, d8);
        final kh1.d d9 = new kh1.d(a3, rj.a(), new lh1.a(new k51.e()), new k51.e());
        final wa0.b t11 = ((e0)a4.a).T6();
        zd.b.r(t11);
        final kh1.c c7 = new kh1.c(t11);
        final nb0.a p7 = ((e0)a4.a).P0();
        zd.b.r(p7);
        final lg1.e e7 = new lg1.e(a3, rj.a());
        final nb0.a p8 = ((e0)a4.a).P0();
        zd.b.r(p8);
        final lg1.a a10 = new lg1.a(a3, e7, p8);
        final lg1.e e8 = new lg1.e(a3, rj.a());
        final lg1.f f12 = new lg1.f();
        final dw0.a a11 = ((e0)a4.a).a();
        zd.b.r(a11);
        final lg1.b b2 = new lg1.b(e8, f12, a11);
        final dw0.a a12 = ((e0)a4.a).a();
        zd.b.r(a12);
        final NotificationComposer notificationComposer = new NotificationComposer(notificationImageComposer, e6, d9, c7, new kh1.b(new lg1.c(p7, a10, b2, a12), new lh1.a(new k51.e())), new jh1.a(a3, new jh1.b()), rj.c());
        final Context l6 = ((e0)a4.a).l();
        zd.b.r(l6);
        final ih1.d d10 = new ih1.d();
        final jh1.d c8 = rj.c();
        final wa0.b t12 = ((e0)a4.a).T6();
        zd.b.r(t12);
        debugActivity.M = new PushNotificationController(d5, a6, j6, f10, c5, h2, notificationComposer, new og1.d(l6, d10, c8, t12));
        final w70.h h3 = ((e0)a4.a).H0();
        zd.b.r(h3);
        debugActivity.N = h3;
        final qy1.j k2 = ((e0)a4.a).K3();
        zd.b.r(k2);
        debugActivity.O = k2;
        debugActivity.P = (dy1.a)a4.U3();
        debugActivity.Q = (z20.a)a4.F0();
        return new ht((Object)rj);
    }
}
