// 
// Decompiled by Procyon v0.6.0
// 

package w90;

import of0.k0;
import e40.k;
import in0.v;
import rh0.b$a;
import com.reddit.screen.BaseScreen;
import com.reddit.events.common.AnalyticsScreenReferrer;
import ul0.h;
import q20.c;
import n42.g;
import in0.j;
import uz.i;
import com.reddit.events.postsets.PostSetAnalytics;
import com.reddit.events.creatorstats.CreatorStatsAnalytics;
import com.reddit.common.localization.translations.TranslationsAnalytics;
import com.reddit.events.blocked.BlockedAccountsAnalytics;
import pi0.a;
import com.reddit.events.recommendations.RecommendationAnalytics;
import com.reddit.events.usermodal.UserModalAnalytics;
import w30.d;
import com.reddit.billing.RedditBillingManager;
import com.reddit.billing.RemotePurchaseDataSource;
import javax.inject.Provider;
import sa1.b;
import ca0.o0;
import zy.e;

public final class ig
{
    public e A;
    public o0 B;
    public b C;
    public Provider<RemotePurchaseDataSource> D;
    public py.b E;
    public Provider<RedditBillingManager> F;
    public d G;
    public e H;
    public vx.d I;
    public Provider<UserModalAnalytics> J;
    public Provider<RecommendationAnalytics> K;
    public Provider<a> L;
    public mw.b M;
    public Provider<p42.a> N;
    public x40.a O;
    public cx.b P;
    public Provider<BlockedAccountsAnalytics> Q;
    public Provider<fx.a> R;
    public Provider<TranslationsAnalytics> S;
    public n20.b T;
    public Provider<CreatorStatsAnalytics> U;
    public Provider<PostSetAnalytics> V;
    public Provider<in0.o0> W;
    public af2.e a;
    public iv0.b b;
    public af2.e c;
    public Provider<ls1.a> d;
    public r40.a e;
    public Provider<rh0.a> f;
    public i g;
    public Provider<j> h;
    public Provider<o20.a> i;
    public Provider<vt0.a> j;
    public af2.e k;
    public af2.e l;
    public Provider<g> m;
    public yq1.d n;
    public ei1.a o;
    public v10.e p;
    public mx.b q;
    public Provider<jl0.d> r;
    public a40.g s;
    public Provider<c> t;
    public ms1.a u;
    public Provider<jl0.a> v;
    public Provider<com.reddit.screens.listing.mapper.a> w;
    public Provider<wh0.a> x;
    public h y;
    public Provider<fo0.a> z;
    
    public ig(final a1 a1, final String s, final AnalyticsScreenReferrer analyticsScreenReferrer, final String s2, final BaseScreen baseScreen) {
        final af2.e a2 = af2.e.a((Object)baseScreen);
        this.a = a2;
        this.b = iv0.b.b((Provider)a2);
        this.c = af2.e.a((Object)s2);
        this.d = (Provider<ls1.a>)af2.c.b((Provider)sy.e.a((Provider)this.b, (Provider)this.a, (Provider)a1.w, (Provider)a1.T, (Provider)a1.U, (Provider)a1.V));
        this.e = r40.a.a((Provider)this.b, ms1.a.a((Provider)a1.b0, (Provider)a1.y), (Provider)a1.m, (Provider)a1.z0, (Provider)a1.A0);
        this.f = (Provider<rh0.a>)af2.c.b((Provider)b$a.a);
        final i c = uz.i.c((Provider)a1.x0, (Provider)a1.y0);
        this.g = c;
        this.h = (Provider<j>)af2.c.b((Provider)in0.v.a((Provider)this.b, (Provider)this.a, (Provider)this.c, (Provider)a1.b0, (Provider)a1.E, (Provider)a1.m2, (Provider)this.d, (Provider)a1.n3, (Provider)a1.M1, (Provider)this.e, (Provider)a1.R1, (Provider)a1.n, (Provider)this.f, (Provider)a1.o3, (Provider)a1.h, (Provider)a1.p3, (Provider)c, (Provider)a1.n2, (Provider)a1.A1, (Provider)a1.S1, (Provider)a1.j1, (Provider)a1.J0));
        this.i = (Provider<o20.a>)af2.c.b((Provider)vx.d.b((Provider)this.b, (Provider)a1.E, (Provider)a1.w));
        this.j = (Provider<vt0.a>)af2.c.b((Provider)ug0.a.c(xb0.b.e(e40.k.b((Provider)a1.l0, (Provider)a1.m0, (Provider)a1.e))));
        this.k = af2.e.a((Object)s);
        this.l = af2.e.b((Object)analyticsScreenReferrer);
        final Provider b = af2.c.b((Provider)ei1.a.b((Provider)this.b));
        this.m = (Provider<g>)b;
        this.n = yq1.d.a(b, (Provider)a1.d0);
        this.o = ei1.a.c((Provider)a1.m);
        this.p = v10.e.a((Provider)a1.c0, (Provider)a1.m, (Provider)this.b, (Provider)a1.n, (Provider)a1.i, (Provider)a1.B2, (Provider)a1.V, (Provider)this.o, (Provider)mw.b.b(), (Provider)a1.i0, (Provider)a1.C2);
        this.q = mx.b.a((Provider)ht.b.b());
        this.r = (Provider<jl0.d>)af2.h.a((Provider)jl0.i.a((Provider)a1.m));
        this.s = a40.g.a((Provider)a1.m, (Provider)this.r, (Provider)a1.n, (Provider)vg0.a.b((Provider)a1.j), (Provider)a1.i, (Provider)a1.o, (Provider)a1.p, (Provider)a1.q);
        final Provider b2 = af2.c.b((Provider)ei1.a.a((Provider)this.b));
        this.t = (Provider<c>)b2;
        this.u = ms1.a.b(b2, (Provider)a1.z0);
        final Provider a3 = af2.h.a((Provider)jl0.g.a((Provider)a1.m));
        this.v = (Provider<jl0.a>)a3;
        this.w = (Provider<com.reddit.screens.listing.mapper.a>)af2.c.b((Provider)x10.j.b(a3, (Provider)a1.j, (Provider)a1.G, (Provider)a1.c, (Provider)this.g));
        final Provider b3 = af2.c.b((Provider)vg0.a.d((Provider)a1.h));
        this.x = (Provider<wh0.a>)b3;
        this.y = ul0.h.a((Provider)a1.c, (Provider)a1.j, (Provider)a1.Y, (Provider)a1.z2, (Provider)this.n, (Provider)a1.c0, (Provider)a1.A2, (Provider)a1.d0, (Provider)this.p, (Provider)this.q, (Provider)a1.D2, (Provider)this.s, (Provider)a1.m, (Provider)a1.E2, (Provider)a1.k1, (Provider)a1.r2, (Provider)a1.F2, (Provider)a1.R1, (Provider)a1.V, (Provider)a1.P1, (Provider)this.u, (Provider)a1.J1, (Provider)this.w, (Provider)p40.a.d((Provider)a1.r2, (Provider)a1.J1, (Provider)this.t, b3));
        this.z = (Provider<fo0.a>)af2.c.b((Provider)vx.d.c((Provider)this.b, (Provider)a1.N2, (Provider)a1.w));
        this.A = zy.e.a((Provider)a1.y, (Provider)a1.e, (Provider)a1.o0);
        this.B = o0.e((Provider)a1.h);
        this.C = sa1.b.a((Provider)this.a);
        final Provider a4 = af2.h.a((Provider)rx.b.a((Provider)a1.D0));
        this.D = (Provider<RemotePurchaseDataSource>)a4;
        this.E = py.b.a(a4, (Provider)a1.E0);
        final Provider b4 = af2.c.b((Provider)vx.c.b((Provider)this.b, (Provider)this.C, (Provider)this.E, (Provider)a1.c, (Provider)a1.b0, (Provider)a1.F0, (Provider)a1.G0, (Provider)a1.o0, (Provider)a1.m, (Provider)uz.i.a((Provider)a1.c, (Provider)a1.K), (Provider)a1.H0, (Provider)a1.V));
        this.F = (Provider<RedditBillingManager>)b4;
        this.G = w30.d.a(this.d, (Provider)a1.X, (Provider)a1.e, (Provider)a1.o0, (Provider)a1.V, (Provider)ty.e.a((Provider)a1.X, (Provider)a1.V, (Provider)a1.a0, (Provider)a1.n, (Provider)a1.c3, (Provider)a1.c, b4, (Provider)a1.r, (Provider)a1.J));
        this.H = zy.e.b((Provider)this.b, (Provider)a1.w, (Provider)a1.T);
        this.I = vx.d.a((Provider)this.b, (Provider)this.a, (Provider)a1.w);
        this.J = (Provider<UserModalAnalytics>)af2.c.b((Provider)xb0.b.d((Provider)a1.h));
        this.K = (Provider<RecommendationAnalytics>)af2.c.b((Provider)vx.b.b((Provider)a1.h, (Provider)this.f));
        this.L = (Provider<a>)af2.c.b((Provider)mx.b.b((Provider)a1.h, (Provider)this.f));
        this.M = mw.b.a((Provider)a1.h);
        this.N = (Provider<p42.a>)af2.c.b((Provider)nx.d.a((Provider)this.C, (Provider)a1.i, (Provider)a1.y, (Provider)a1.k1, (Provider)a1.T0, (Provider)a1.m, py.b.b((Provider)a1.h, (Provider)this.k), (Provider)a1.e, (Provider)a1.o0));
        this.O = x40.a.a((Provider)a1.w, (Provider)a1.r0, (Provider)a1.s0, (Provider)a1.t0, (Provider)this.b, (Provider)a1.u0, (Provider)d00.c.e((Provider)a1.v0, (Provider)a1.t0), (Provider)a1.v0);
        this.P = cx.b.c((Provider)this.b, (Provider)this.a, (Provider)a1.w, (Provider)a1.T, (Provider)a1.d3);
        this.Q = (Provider<BlockedAccountsAnalytics>)af2.c.b((Provider)k0.b((Provider)a1.h));
        this.R = (Provider<fx.a>)af2.c.b((Provider)gx.b.a((Provider)a1.v1, (Provider)a1.t0, (Provider)a1.n, (Provider)a1.w1, (Provider)a1.J, (Provider)a1.L));
        final Provider b5 = af2.c.b((Provider)rx.a.b((Provider)a1.h));
        this.S = (Provider<TranslationsAnalytics>)b5;
        this.T = n20.b.a((Provider)this.b, (Provider)a1.t3, (Provider)a1.w, b5);
        this.U = (Provider<CreatorStatsAnalytics>)af2.c.b((Provider)ug0.a.d((Provider)a1.h));
        final Provider b6 = af2.c.b((Provider)o0.c((Provider)a1.h));
        this.V = (Provider<PostSetAnalytics>)b6;
        this.W = (Provider<in0.o0>)af2.c.b((Provider)in0.k0.a((Provider)this.b, (Provider)this.h, (Provider)a1.i, (Provider)this.i, (Provider)a1.d, (Provider)a1.x1, (Provider)this.j, (Provider)this.k, (Provider)this.l, (Provider)this.y, (Provider)this.z, (Provider)a1.N2, (Provider)a1.q3, (Provider)a1.e, (Provider)a1.o0, (Provider)this.A, (Provider)a1.r3, (Provider)a1.i2, (Provider)a1.d0, (Provider)a1.W, (Provider)this.B, (Provider)this.G, (Provider)this.H, (Provider)this.I, (Provider)this.J, (Provider)this.n, (Provider)this.K, (Provider)this.L, (Provider)a1.h, (Provider)a1.R1, (Provider)this.M, (Provider)this.N, (Provider)a1.e2, (Provider)this.O, (Provider)this.P, (Provider)this.Q, (Provider)a1.s3, (Provider)this.R, (Provider)this.f, (Provider)a1.w0, (Provider)this.a, (Provider)a1.J0, (Provider)a1.b2, (Provider)a1.r, (Provider)this.T, (Provider)a1.h3, (Provider)a1.d2, (Provider)a1.c, (Provider)this.v, (Provider)a1.j, (Provider)this.U, (Provider)a1.u1, (Provider)a1.u3, (Provider)a1.w, (Provider)a1.G, (Provider)a1.S1, b6, (Provider)a1.I1, (Provider)a1.c2, (Provider)a1.y0, (Provider)a1.j1, (Provider)a1.A1, (Provider)a1.v3));
    }
}
