// 
// Decompiled by Procyon v0.6.0
// 

package w90;

import bt0.s;
import of0.v1;
import vs1.c$a;
import rl0.v$a;
import rl0.w$a;
import rl0.x$a;
import of0.k0;
import rh0.b$a;
import com.reddit.events.common.AnalyticsScreenReferrer;
import com.reddit.events.onboardingchaining.OnboardingChainingAnalytics;
import com.reddit.screens.profile.submitted.UserSubmittedListingPresenter;
import java.util.Calendar;
import com.reddit.events.userprofile.UserProfileAnalytics;
import n42.g;
import of0.c0;
import in0.v;
import uz.i;
import bx.k;
import ou0.c;
import com.reddit.events.postsets.PostSetAnalytics;
import com.reddit.events.creatorstats.CreatorStatsAnalytics;
import com.reddit.common.localization.translations.TranslationsAnalytics;
import com.reddit.events.blocked.BlockedAccountsAnalytics;
import com.reddit.screen.BaseScreen;
import com.reddit.events.recommendations.RecommendationAnalytics;
import com.reddit.events.usermodal.UserModalAnalytics;
import w30.d;
import com.reddit.billing.RedditBillingManager;
import com.reddit.billing.RemotePurchaseDataSource;
import af2.e;
import in0.j;
import v11.f;
import ca0.o0;
import kz0.b;
import ul0.h;
import in0.m;
import javax.inject.Provider;
import p40.a;

public final class kg
{
    public a A;
    public Provider<m> A0;
    public h B;
    public Provider<b> B0;
    public cx.b C;
    public o0 D;
    public Provider<f> E;
    public Provider<j> F;
    public Provider<o20.a> G;
    public Provider<vt0.a> H;
    public e I;
    public e J;
    public Provider<fo0.a> K;
    public zy.e L;
    public o0 M;
    public sa1.b N;
    public Provider<RemotePurchaseDataSource> O;
    public py.b P;
    public Provider<RedditBillingManager> Q;
    public d R;
    public zy.e S;
    public vx.d T;
    public Provider<UserModalAnalytics> U;
    public Provider<RecommendationAnalytics> V;
    public Provider<pi0.a> W;
    public mw.b X;
    public Provider<p42.a> Y;
    public x40.a Z;
    public final BaseScreen a;
    public Provider<BlockedAccountsAnalytics> a0;
    public final String b;
    public Provider<fx.a> b0;
    public final a1 c;
    public Provider<TranslationsAnalytics> c0;
    public e d;
    public n20.b d0;
    public e e;
    public Provider<CreatorStatsAnalytics> e0;
    public iv0.b f;
    public Provider<PostSetAnalytics> f0;
    public e g;
    public Provider<in0.o0> g0;
    public Provider<ls1.a> h;
    public Provider<c> h0;
    public r40.a i;
    public k i0;
    public Provider<rh0.a> j;
    public o52.e j0;
    public i k;
    public d k0;
    public v l;
    public d00.c l0;
    public Provider<ru0.a> m;
    public n41.d m0;
    public Provider<c0> n;
    public Provider<t72.a> n0;
    public Provider<q20.c> o;
    public l40.a o0;
    public Provider<g> p;
    public Provider<UserProfileAnalytics> p0;
    public yq1.d q;
    public Provider<oi0.c> q0;
    public ei1.a r;
    public Provider<Calendar> r0;
    public v10.e s;
    public Provider<et1.b> s0;
    public mx.b t;
    public Provider<et1.a> t0;
    public Provider<jl0.d> u;
    public Provider<UserSubmittedListingPresenter> u0;
    public a40.g v;
    public xb0.b v0;
    public ms1.a w;
    public Provider<OnboardingChainingAnalytics> w0;
    public Provider<jl0.a> x;
    public hm0.d x0;
    public Provider<com.reddit.screens.listing.mapper.a> y;
    public Provider<vs1.b> y0;
    public Provider<wh0.a> z;
    public Provider<vs1.a> z0;
    
    public kg(final a1 c, final su1.b b, final BaseScreen a, final String b2, final AnalyticsScreenReferrer analyticsScreenReferrer) {
        this.c = c;
        this.a = a;
        this.b = b2;
        this.d = af2.e.a((Object)b);
        final e a2 = af2.e.a((Object)a);
        this.e = a2;
        this.f = iv0.b.b((Provider)a2);
        this.g = af2.e.a((Object)"profile");
        this.h = (Provider<ls1.a>)af2.c.b((Provider)sy.e.a((Provider)this.f, (Provider)this.e, (Provider)c.w, (Provider)c.T, (Provider)c.U, (Provider)c.V));
        this.i = r40.a.a((Provider)this.f, ms1.a.a((Provider)c.b0, (Provider)c.y), (Provider)c.m, (Provider)c.z0, (Provider)c.A0);
        this.j = (Provider<rh0.a>)af2.c.b((Provider)b$a.a);
        final i c2 = uz.i.c((Provider)c.x0, (Provider)c.y0);
        this.k = c2;
        final v a3 = in0.v.a((Provider)this.f, (Provider)this.e, (Provider)this.g, (Provider)c.b0, (Provider)c.E, (Provider)c.m2, (Provider)this.h, (Provider)c.n3, (Provider)c.M1, (Provider)this.i, (Provider)c.R1, (Provider)c.n, (Provider)this.j, (Provider)c.o3, (Provider)c.h, (Provider)c.p3, (Provider)c2, (Provider)c.n2, (Provider)c.A1, (Provider)c.S1, (Provider)c.j1, (Provider)c.J0);
        this.l = a3;
        this.m = (Provider<ru0.a>)af2.c.b((Provider)a3);
        this.n = (Provider<c0>)af2.c.b((Provider)new of0.b((Provider)c.x1, 1));
        this.o = (Provider<q20.c>)af2.c.b((Provider)ei1.a.a((Provider)this.f));
        final Provider b3 = af2.c.b((Provider)ei1.a.b((Provider)this.f));
        this.p = (Provider<g>)b3;
        this.q = yq1.d.a(b3, (Provider)c.d0);
        this.r = ei1.a.c((Provider)c.m);
        this.s = v10.e.a((Provider)c.c0, (Provider)c.m, (Provider)this.f, (Provider)c.n, (Provider)c.i, (Provider)c.B2, (Provider)c.V, (Provider)this.r, (Provider)mw.b.b(), (Provider)c.i0, (Provider)c.C2);
        this.t = mx.b.a((Provider)ht.b.b());
        this.u = (Provider<jl0.d>)af2.h.a((Provider)jl0.i.a((Provider)c.m));
        this.v = a40.g.a((Provider)c.m, (Provider)this.u, (Provider)c.n, (Provider)vg0.a.b((Provider)c.j), (Provider)c.i, (Provider)c.o, (Provider)c.p, (Provider)c.q);
        this.w = ms1.a.b((Provider)this.o, (Provider)c.z0);
        final Provider a4 = af2.h.a((Provider)jl0.g.a((Provider)c.m));
        this.x = (Provider<jl0.a>)a4;
        this.y = (Provider<com.reddit.screens.listing.mapper.a>)af2.c.b((Provider)x10.j.b(a4, (Provider)c.j, (Provider)c.G, (Provider)c.c, (Provider)this.k));
        final Provider b4 = af2.c.b((Provider)vg0.a.d((Provider)c.h));
        this.z = (Provider<wh0.a>)b4;
        final a d = p40.a.d((Provider)c.r2, (Provider)c.J1, (Provider)this.o, b4);
        this.A = d;
        this.B = ul0.h.a((Provider)c.c, (Provider)c.j, (Provider)c.Y, (Provider)c.z2, (Provider)this.q, (Provider)c.c0, (Provider)c.A2, (Provider)c.d0, (Provider)this.s, (Provider)this.t, (Provider)c.D2, (Provider)this.v, (Provider)c.m, (Provider)c.E2, (Provider)c.k1, (Provider)c.r2, (Provider)c.F2, (Provider)c.R1, (Provider)c.V, (Provider)c.P1, (Provider)this.w, (Provider)c.J1, (Provider)this.y, (Provider)d);
        this.C = cx.b.c((Provider)this.f, (Provider)this.e, (Provider)c.w, (Provider)c.T, (Provider)c.d3);
        final o0 d2 = ca0.o0.d((Provider)c.h);
        this.D = d2;
        this.E = (Provider<f>)af2.h.a((Provider)rl0.g.a((Provider)this.f, (Provider)c.x1, (Provider)this.e, (Provider)c.o0, (Provider)c.r, (Provider)this.C, (Provider)c.w3, (Provider)c.V, d2, (Provider)c.C2, (Provider)c.l1, (Provider)c.x3));
        this.F = (Provider<j>)af2.c.b((Provider)this.l);
        this.G = (Provider<o20.a>)af2.c.b((Provider)vx.d.b((Provider)this.f, (Provider)c.E, (Provider)c.w));
        this.H = (Provider<vt0.a>)af2.c.b((Provider)ug0.a.c(xb0.b.e(e40.k.b((Provider)c.l0, (Provider)c.m0, (Provider)c.e))));
        this.I = af2.e.b((Object)b2);
        this.J = af2.e.b((Object)analyticsScreenReferrer);
        this.K = (Provider<fo0.a>)af2.c.b((Provider)vx.d.c((Provider)this.f, (Provider)c.N2, (Provider)c.w));
        this.L = zy.e.a((Provider)c.y, (Provider)c.e, (Provider)c.o0);
        this.M = ca0.o0.e((Provider)c.h);
        this.N = sa1.b.a((Provider)this.e);
        final Provider a5 = af2.h.a((Provider)rx.b.a((Provider)c.D0));
        this.O = (Provider<RemotePurchaseDataSource>)a5;
        this.P = py.b.a(a5, (Provider)c.E0);
        final Provider b5 = af2.c.b((Provider)vx.c.b((Provider)this.f, (Provider)this.N, (Provider)this.P, (Provider)c.c, (Provider)c.b0, (Provider)c.F0, (Provider)c.G0, (Provider)c.o0, (Provider)c.m, (Provider)uz.i.a((Provider)c.c, (Provider)c.K), (Provider)c.H0, (Provider)c.V));
        this.Q = (Provider<RedditBillingManager>)b5;
        this.R = w30.d.a(this.h, (Provider)c.X, (Provider)c.e, (Provider)c.o0, (Provider)c.V, (Provider)ty.e.a((Provider)c.X, (Provider)c.V, (Provider)c.a0, (Provider)c.n, (Provider)c.c3, (Provider)c.c, b5, (Provider)c.r, (Provider)c.J));
        this.S = zy.e.b((Provider)this.f, (Provider)c.w, (Provider)c.T);
        this.T = vx.d.a((Provider)this.f, (Provider)this.e, (Provider)c.w);
        this.U = (Provider<UserModalAnalytics>)af2.c.b((Provider)xb0.b.d((Provider)c.h));
        this.V = (Provider<RecommendationAnalytics>)af2.c.b((Provider)vx.b.b((Provider)c.h, (Provider)this.j));
        this.W = (Provider<pi0.a>)af2.c.b((Provider)mx.b.b((Provider)c.h, (Provider)this.j));
        this.X = mw.b.a((Provider)c.h);
        this.Y = (Provider<p42.a>)af2.c.b((Provider)nx.d.a((Provider)this.N, (Provider)c.i, (Provider)c.y, (Provider)c.k1, (Provider)c.T0, (Provider)c.m, py.b.b((Provider)c.h, (Provider)this.I), (Provider)c.e, (Provider)c.o0));
        this.Z = x40.a.a((Provider)c.w, (Provider)c.r0, (Provider)c.s0, (Provider)c.t0, (Provider)this.f, (Provider)c.u0, (Provider)d00.c.e((Provider)c.v0, (Provider)c.t0), (Provider)c.v0);
        this.a0 = (Provider<BlockedAccountsAnalytics>)af2.c.b((Provider)of0.k0.b((Provider)c.h));
        this.b0 = (Provider<fx.a>)af2.c.b((Provider)gx.b.a((Provider)c.v1, (Provider)c.t0, (Provider)c.n, (Provider)c.w1, (Provider)c.J, (Provider)c.L));
        final Provider b6 = af2.c.b((Provider)rx.a.b((Provider)c.h));
        this.c0 = (Provider<TranslationsAnalytics>)b6;
        this.d0 = n20.b.a((Provider)this.f, (Provider)c.t3, (Provider)c.w, b6);
        this.e0 = (Provider<CreatorStatsAnalytics>)af2.c.b((Provider)ug0.a.d((Provider)c.h));
        final Provider b7 = af2.c.b((Provider)ca0.o0.c((Provider)c.h));
        this.f0 = (Provider<PostSetAnalytics>)b7;
        this.g0 = (Provider<in0.o0>)af2.c.b((Provider)in0.k0.a((Provider)this.f, (Provider)this.F, (Provider)c.i, (Provider)this.G, (Provider)c.d, (Provider)c.x1, (Provider)this.H, (Provider)this.I, (Provider)this.J, (Provider)this.B, (Provider)this.K, (Provider)c.N2, (Provider)c.q3, (Provider)c.e, (Provider)c.o0, (Provider)this.L, (Provider)c.r3, (Provider)c.i2, (Provider)c.d0, (Provider)c.W, (Provider)this.M, (Provider)this.R, (Provider)this.S, (Provider)this.T, (Provider)this.U, (Provider)this.q, (Provider)this.V, (Provider)this.W, (Provider)c.h, (Provider)c.R1, (Provider)this.X, (Provider)this.Y, (Provider)c.e2, (Provider)this.Z, (Provider)this.C, (Provider)this.a0, (Provider)c.s3, (Provider)this.b0, (Provider)this.j, (Provider)c.w0, (Provider)this.e, (Provider)c.J0, (Provider)c.b2, (Provider)c.r, (Provider)this.d0, (Provider)c.h3, (Provider)c.d2, (Provider)c.c, (Provider)this.x, (Provider)c.j, (Provider)this.e0, (Provider)c.u1, (Provider)c.u3, (Provider)c.w, (Provider)c.G, (Provider)c.S1, b7, (Provider)c.I1, (Provider)c.c2, (Provider)c.y0, (Provider)c.j1, (Provider)c.A1, (Provider)c.v3));
        this.h0 = (Provider<c>)af2.c.b((Provider)x$a.a);
        this.i0 = bx.k.a((Provider)c.A2, (Provider)c.E2);
        this.j0 = o52.e.a((Provider)this.w, (Provider)c.m, (Provider)c.P1);
        this.k0 = w30.d.c((Provider)this.i0, (Provider)this.j0, v40.d.a((Provider)c.Y, (Provider)c.c0, (Provider)this.q, (Provider)c.d0), (Provider)c.j, (Provider)c.z2, (Provider)this.A);
        this.l0 = d00.c.a((Provider)this.N, (Provider)c.w);
        this.m0 = n41.d.c((Provider)this.N);
        final Provider b8 = af2.c.b((Provider)w$a.a);
        this.n0 = (Provider<t72.a>)b8;
        this.o0 = l40.a.b((Provider)c.G, (Provider)c.y3, (Provider)c.P0, (Provider)this.l0, (Provider)this.m0, b8);
        this.p0 = (Provider<UserProfileAnalytics>)af2.c.b((Provider)of0.k0.a((Provider)c.h));
        this.q0 = (Provider<oi0.c>)af2.c.b((Provider)vg0.a.a((Provider)c.h));
        this.r0 = (Provider<Calendar>)af2.c.b((Provider)v$a.a);
        final Provider b9 = af2.c.b((Provider)new sx.b((Provider)this.f, (Provider)c.w, (Provider)this.i, (Provider)c.J0, (Provider)c.c1, 10));
        this.s0 = (Provider<et1.b>)b9;
        final Provider b10 = af2.c.b((Provider)new hx.a((Provider)this.f, (Provider)this.x, b9, (Provider)this.f0, 19));
        this.t0 = (Provider<et1.a>)b10;
        this.u0 = (Provider<UserSubmittedListingPresenter>)af2.c.b((Provider)new su1.c((Provider)this.d, c.b0, (Provider)this.m, c.D4, c.d, c.o0, c.e, (Provider)this.n, (Provider)this.o, (Provider)this.B, (Provider)this.E, (Provider)this.g0, c.j, c.j2, c.c, c.d2, (Provider)this.h0, (Provider)this.k0, c.V, c.C2, (Provider)this.o0, (Provider)this.p0, c.z3, c.c0, (Provider)this.q0, (Provider)this.C, (Provider)this.s, c.i, c.B2, (Provider)this.D, c.e2, c.f2, (Provider)this.G, (Provider)this.r0, c.j1, c.h2, c.L, (Provider)this.x, c.h1, c.g1, c.K2, b10));
        this.v0 = xb0.b.a((Provider)c.h);
        this.w0 = (Provider<OnboardingChainingAnalytics>)af2.c.b((Provider)ca0.o0.b((Provider)c.h));
        this.x0 = hm0.d.a((Provider)c.L1, (Provider)c.M1, (Provider)c.g2, (Provider)c.V, (Provider)c.B3, (Provider)c.l1, (Provider)this.v0, (Provider)c.C3, (Provider)c.J0, (Provider)this.W, (Provider)c.h2, (Provider)this.j, (Provider)c.y0, (Provider)c.f2, (Provider)c.v0, (Provider)c.u2, (Provider)this.x, (Provider)c.D3, (Provider)c.R1, (Provider)c.N1, (Provider)this.w0, (Provider)c.z0, (Provider)c.S1, (Provider)c.P2, (Provider)c.q, (Provider)c.J1, (Provider)ca0.o0.a((Provider)c.h), (Provider)c.u1, (Provider)c.s1, (Provider)c.u3, (Provider)c.i, (Provider)c.k3, (Provider)c.E3, (Provider)c.F3, (Provider)c.G3, (Provider)c.M0, (Provider)c.j0, (Provider)c.Z1, (Provider)this.I);
        final Provider b11 = af2.c.b((Provider)c$a.a);
        this.y0 = (Provider<vs1.b>)b11;
        final Provider b12 = af2.c.b((Provider)cx.b.a(b11, (Provider)c.q1, (Provider)c.L1, (Provider)c.M1, (Provider)c.R1));
        this.z0 = (Provider<vs1.a>)b12;
        this.A0 = (Provider<m>)af2.c.b((Provider)hx.a.a((Provider)c.g2, (Provider)this.x0, b12, (Provider)c.w));
        this.B0 = (Provider<b>)af2.c.b((Provider)ca0.o0.g((Provider)c.h));
    }
    
    public final v1 a() {
        final q20.b k4 = this.c.a.k4();
        kz0.k.N((Object)k4);
        final s o2 = this.c.a.O2();
        kz0.k.N((Object)o2);
        final r41.a y3 = this.c.a.y3();
        kz0.k.N((Object)y3);
        return new v1(k4, o2, y3);
    }
}
